export const DEMONSTRATIVE_ZONES = [
  {
    id: 'zone1_close',
    title: '1. ESTE — ACÁ / AQUÍ',
    subtitle: 'Близко (тут, у меня / в зоне досягаемости)',
    mnemonic: '«Этот ЭСТЭт любит свой АКа! ❤️»',
    adverbs: [
      { es: 'acá', ru: 'тут, здесь (разговорный, Латинская Америка)' },
      { es: 'aquí', ru: 'здесь (точная точка, классический)' },
    ],
    forms: [
      { es: 'este', ru: 'этот', gender: 'm.sg', ex: 'Este café está muy caliente.' },
      { es: 'esta', ru: 'эта', gender: 'f.sg', ex: 'Esta casa es muy luminosa.' },
      { es: 'estos', ru: 'эти', gender: 'm.pl', ex: 'Estos libros son interesantes.' },
      { es: 'estas', ru: 'эти', gender: 'f.pl', ex: 'Estas flores huelen muy bien.' },
      { es: 'esto', ru: 'это (нейтральное)', gender: 'neuter', ex: '¿Qué es esto? No sé qué es.' },
    ],
    color: 'from-emerald-500 to-teal-600',
    border: 'border-emerald-200 dark:border-emerald-800',
    bg: 'bg-emerald-50 dark:bg-emerald-950/30',
    tagBg: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/60 dark:text-emerald-200',
  },
  {
    id: 'zone2_medium',
    title: '2. ESE — AHÍ',
    subtitle: 'Средняя дистанция (там, у собеседника / недалеко)',
    mnemonic: '«То ЭСЭ написано АИ!»',
    adverbs: [
      { es: 'ahí', ru: 'там (у тебя, рядом, в поле зрения)' },
    ],
    forms: [
      { es: 'ese', ru: 'тот / этот (у тебя)', gender: 'm.sg', ex: 'Pásame ese lápiz que tienes ahí.' },
      { es: 'esa', ru: 'та / эта (у тебя)', gender: 'f.sg', ex: 'Esa camisa te queda perfecta.' },
      { es: 'esos', ru: 'те / эти (у тебя)', gender: 'm.pl', ex: 'Esos zapatos son cómodos.' },
      { es: 'esas', ru: 'те / эти (у тебя)', gender: 'f.pl', ex: 'Esas llaves son mías.' },
      { es: 'eso', ru: 'то (нейтральное)', gender: 'neuter', ex: 'Eso que dijiste es muy cierto.' },
    ],
    color: 'from-amber-500 to-orange-600',
    border: 'border-amber-200 dark:border-amber-800',
    bg: 'bg-amber-50 dark:bg-amber-950/30',
    tagBg: 'bg-amber-100 text-amber-800 dark:bg-amber-900/60 dark:text-amber-200',
  },
  {
    id: 'zone3_far',
    title: '3. AQUEL — ALLÁ / ALLÍ',
    subtitle: 'Далеко (вон там, далеко от обоих говорящих)',
    mnemonic: '«Акела АЖ таАм!» (с акцентом на «АША» для allá)',
    adverbs: [
      { es: 'allí', ru: 'вон там (конкретное далекое место)' },
      { es: 'allá', ru: 'вон там вдалеке (произношение «аша» в Аргентине)' },
    ],
    forms: [
      { es: 'aquel', ru: 'вон тот', gender: 'm.sg', ex: 'Aquel edificio a lo lejos es el museo.' },
      { es: 'aquella', ru: 'вон та', gender: 'f.sg', ex: 'Aquella montaña tiene nieve en la cima.' },
      { es: 'aquellos', ru: 'вон те', gender: 'm.pl', ex: 'Aquellos árboles son muy antiguos.' },
      { es: 'aquellas', ru: 'вон те', gender: 'f.pl', ex: 'Aquellas nubes anuncian lluvia.' },
      { es: 'aquello', ru: 'вон то (нейтральное)', gender: 'neuter', ex: 'Aquello que pasó fue inolvidable.' },
    ],
    color: 'from-indigo-500 to-purple-600',
    border: 'border-indigo-200 dark:border-indigo-800',
    bg: 'bg-indigo-50 dark:bg-indigo-950/30',
    tagBg: 'bg-indigo-100 text-indigo-800 dark:bg-indigo-900/60 dark:text-indigo-200',
  },
];

export const DEMONSTRATIVE_DRILL_QUESTIONS = [
  // --- ZONE 1: ESTE / ESTA / ESTOS / ESTAS / ESTO / ACÁ / AQUÍ ---
  {
    id: 1,
    category: 'forms',
    distance: 'zone1_close',
    sentence: '___ libro que tengo en mi mano es muy interesante.',
    translation: 'Эта книга, которую я держу в руке, очень интересная.',
    distanceHint: '📍 Близко (в руке у меня / acá)',
    options: ['Este', 'Ese', 'Aquel', 'Esta'],
    correctAnswer: 'Este',
    explanation: '«Libro» — мужской род, ед. число. Так как книга в руках у говорящего (дистанция 1), выбираем ESTE.',
    exampleAudio: 'Este libro que tengo en mi mano es muy interesante.',
  },
  {
    id: 2,
    category: 'forms',
    distance: 'zone1_close',
    sentence: '___ manzana está deliciosa, pruébala.',
    translation: 'Это яблоко очень вкусное, попробуй.',
    distanceHint: '📍 Близко (у меня, ем сейчас / aquí)',
    options: ['Esta', 'Este', 'Esa', 'Aquella'],
    correctAnswer: 'Esta',
    explanation: '«Manzana» — женский род, ед. число. Предмет рядом с говорящим, поэтому ESTA.',
    exampleAudio: 'Esta manzana está deliciosa, pruébala.',
  },
  {
    id: 3,
    category: 'forms',
    distance: 'zone1_close',
    sentence: '___ zapatos que llevo puestos son muy cómodos.',
    translation: 'Эти туфли, которые на мне надеты, очень удобные.',
    distanceHint: '📍 Близко (на мне надето / acá)',
    options: ['Estos', 'Esos', 'Aquellos', 'Estas'],
    correctAnswer: 'Estos',
    explanation: '«Zapatos» — мужской род, множ. число. Надеты на говорящем (дистанция 1), поэтому ESTOS.',
    exampleAudio: 'Estos zapatos que llevo puestos son muy cómodos.',
  },
  {
    id: 4,
    category: 'forms',
    distance: 'zone1_close',
    sentence: '___ llaves son las mías, están aquí en mi bolsillo.',
    translation: 'Эти ключи мои, они здесь в моём кармане.',
    distanceHint: '📍 Близко (в кармане у меня / aquí)',
    options: ['Estas', 'Estos', 'Esas', 'Aquellas'],
    correctAnswer: 'Estas',
    explanation: '«Llaves» — женский род, множ. число. Ключи прямо здесь (в кармане), поэтому ESTAS.',
    exampleAudio: 'Estas llaves son las mías, están aquí en mi bolsillo.',
  },
  {
    id: 5,
    category: 'neuter',
    distance: 'zone1_close',
    sentence: '¿Qué es ___? No reconozco este objeto que encontré.',
    translation: 'Что это такое? Я не узнаю этот предмет, который нашёл.',
    distanceHint: '📍 Близко / Неизвестный предмет (esto)',
    options: ['esto', 'este', 'eso', 'aquello'],
    correctAnswer: 'esto',
    explanation: 'Когда мы спрашиваем о неопознанном предмете или явлении в руках/рядом, используем нейтральную форму ESTO (без рода).',
    exampleAudio: '¿Qué es esto? No reconozco este objeto que encontré.',
  },
  {
    id: 6,
    category: 'adverbs',
    distance: 'zone1_close',
    sentence: 'Ven ___, por favor. Quiero mostrarte algo en mi teléfono.',
    translation: 'Иди сюда (тут), пожалуйста. Хочу показать тебе кое-что в телефоне.',
    distanceHint: '📍 Наречие места (сюда / здесь к говорящему)',
    options: ['acá', 'ahí', 'allá', 'allí'],
    correctAnswer: 'acá',
    explanation: 'Приглашение подойти к говорящему: «acá» (или «aquí») означает «тут / сюда / здесь». Ассоциация: «Эстет любит свой АК» (Este — Acá).',
    exampleAudio: 'Ven acá, por favor. Quiero mostrarte algo en mi teléfono.',
  },

  // --- ZONE 2: ESE / ESA / ESOS / ESAS / ESO / AHÍ ---
  {
    id: 7,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: 'Por favor, ¿me pasas ___ bolígrafo que está al lado de tu cuaderno?',
    translation: 'Пожалуйста, передай мне ту ручку, которая лежит рядом с твоей тетрадью?',
    distanceHint: '📍 Средняя дистанция (у собеседника / ahí)',
    options: ['ese', 'este', 'aquel', 'esa'],
    correctAnswer: 'ese',
    explanation: '«Bolígrafo» — мужской род, ед. ч. Предмет находится рядом с собеседником (ahí), поэтому ESE («тот / этот у тебя»).',
    exampleAudio: 'Por favor, ¿me pasas ese bolígrafo que está al lado de tu cuaderno?',
  },
  {
    id: 8,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: '___ chaqueta que llevas puesta te queda genial.',
    translation: 'Та куртка, что на тебе надета, сидит на тебе отлично.',
    distanceHint: '📍 Средняя дистанция (на собеседнике / ahí)',
    options: ['Esa', 'Esta', 'Aquella', 'Ese'],
    correctAnswer: 'Esa',
    explanation: '«Chaqueta» — женский род, ед. число. Вещь на собеседнике (дистанция 2: ese/esa), поэтому ESA.',
    exampleAudio: 'Esa chaqueta que llevas puesta te queda genial.',
  },
  {
    id: 9,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: 'No toques ___ cables que están sobre tu mesa.',
    translation: 'Не трогай те провода, которые на твоём столе.',
    distanceHint: '📍 Средняя дистанция (на твоём столе / ahí)',
    options: ['esos', 'estos', 'aquellos', 'esas'],
    correctAnswer: 'esos',
    explanation: '«Cables» — мужской род, множ. число. Лежат около собеседника, поэтому ESOS.',
    exampleAudio: 'No toques esos cables que están sobre tu mesa.',
  },
  {
    id: 10,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: 'Me gustan mucho ___ gafas que compraste ayer.',
    translation: 'Мне очень нравятся те очки, которые ты купил вчера.',
    distanceHint: '📍 Средняя дистанция (у собеседника / ese)',
    options: ['esas', 'estas', 'aquellas', 'esos'],
    correctAnswer: 'esas',
    explanation: '«Gafas» — женский род, множ. число. Указание на предмет у собеседника: ESAS.',
    exampleAudio: 'Me gustan mucho esas gafas que compraste ayer.',
  },
  {
    id: 11,
    category: 'neuter',
    distance: 'zone2_medium',
    sentence: '___ que acabas de decir es muy importante.',
    translation: 'То, что ты только что сказал, очень важно.',
    distanceHint: '📍 Нейтральное / Мысль или фраза собеседника (eso)',
    options: ['Eso', 'Esto', 'Aquello', 'Ese'],
    correctAnswer: 'Eso',
    explanation: 'Когда мы ссылаемся на слова или мысль собеседника («то, о чем ты сказал»), используется нейтральное ESO.',
    exampleAudio: 'Eso que acabas de decir es muy importante.',
  },
  {
    id: 12,
    category: 'adverbs',
    distance: 'zone2_medium',
    sentence: 'Deja las llaves ___, sobre la mesita junto a la puerta.',
    translation: 'Оставь ключи там, на столике возле двери.',
    distanceHint: '📍 Наречие места (там рядом / aí)',
    options: ['ahí', 'acá', 'allá', 'aquí'],
    correctAnswer: 'ahí',
    explanation: '«Ahí» означает «там» на обозримом среднем расстоянии. Ассоциация: «То ЭСЭ написано АИ» (Ese — Ahí).',
    exampleAudio: 'Deja las llaves ahí, sobre la mesita junto a la puerta.',
  },

  // --- ZONE 3: AQUEL / AQUELLA / AQUELLOS / AQUELLAS / AQUELLO / ALLÁ / ALLÍ ---
  {
    id: 13,
    category: 'forms',
    distance: 'zone3_far',
    sentence: 'Mira ___ barco a lo lejos en el horizonte.',
    translation: 'Посмотри на вон тот корабль вдалеке на горизонте.',
    distanceHint: '📍 Далеко (на горизонте / allá)',
    options: ['aquel', 'este', 'ese', 'aquella'],
    correctAnswer: 'aquel',
    explanation: '«Barco» — мужской род, ед. число. Корабль далеко от обоих говорящих (дистанция 3), поэтому AQUEL («вон тот»).',
    exampleAudio: 'Mira aquel barco a lo lejos en el horizonte.',
  },
  {
    id: 14,
    category: 'forms',
    distance: 'zone3_far',
    sentence: '___ montaña del fondo tiene nieve todo el año.',
    translation: 'Вон та гора на заднем плане покрыта снегом круглый год.',
    distanceHint: '📍 Далеко (на заднем плане / allá)',
    options: ['Aquella', 'Esta', 'Esa', 'Aquel'],
    correctAnswer: 'Aquella',
    explanation: '«Montaña» — женский род, ед. число. Далекий объект на заднем плане: AQUELLA («вон та»).',
    exampleAudio: 'Aquella montaña del fondo tiene nieve todo el año.',
  },
  {
    id: 15,
    category: 'forms',
    distance: 'zone3_far',
    sentence: '¿Ves ___ pájaros volando sobre los árboles lejanos?',
    translation: 'Видишь вон тех птиц, летящих над далёкими деревьями?',
    distanceHint: '📍 Далеко (в небе вдалеке / allá)',
    options: ['aquellos', 'estos', 'esos', 'aquellas'],
    correctAnswer: 'aquellos',
    explanation: '«Pájaros» — мужской род, множ. число. Объекты далеко в небе: AQUELLOS («вон те»).',
    exampleAudio: '¿Ves aquellos pájaros volando sobre los árboles lejanos?',
  },
  {
    id: 16,
    category: 'forms',
    distance: 'zone3_far',
    sentence: 'Recuerdo con cariño ___ vacaciones de nuestra infancia.',
    translation: 'Я с теплом вспоминаю вон те (далёкие) каникулы нашего детства.',
    distanceHint: '📍 Далеко во времени (далекое прошлое / aquel)',
    options: ['aquellas', 'estas', 'esas', 'aquellos'],
    correctAnswer: 'aquellas',
    explanation: '«Vacaciones» — женский род, множ. число. Для событий далекого прошлого используется серия aquel/aquella/aquellas: AQUELLAS.',
    exampleAudio: 'Recuerdo con cariño aquellas vacaciones de nuestra infancia.',
  },
  {
    id: 17,
    category: 'neuter',
    distance: 'zone3_far',
    sentence: '___ que vimos en el cielo anoche fue muy misterioso.',
    translation: 'Вон то (то явление), что мы видели в небе прошлой ночью, было очень загадочным.',
    distanceHint: '📍 Нейтральное / Далекое или прошлое явление (aquello)',
    options: ['Aquello', 'Esto', 'Eso', 'Aquel'],
    correctAnswer: 'Aquello',
    explanation: 'Для далекого во времени или пространстве абстрактного явления/непонятного объекта используется нейтральное AQUELLO.',
    exampleAudio: 'Aquello que vimos en el cielo anoche fue muy misterioso.',
  },
  {
    id: 18,
    category: 'adverbs',
    distance: 'zone3_far',
    sentence: 'El refugio de montaña está ___ arriba, cerca de la cima.',
    translation: 'Горный приют находится вон там наверху, около вершины.',
    distanceHint: '📍 Наречие места (вон там далеко / allá)',
    options: ['allá', 'acá', 'ahí', 'aquí'],
    correctAnswer: 'allá',
    explanation: '«Allá» (или «allí») указывает на далёкое место. Ассоциация: «Акела АЖ таАм!» (Aquel — Allá; в Аргентине произносят «аша»).',
    exampleAudio: 'El refugio de montaña está allá arriba, cerca de la cima.',
  },

  // --- MIXED COMPARISONS & CONTRASTING QUESTIONS ---
  {
    id: 19,
    category: 'forms',
    distance: 'zone1_close',
    sentence: 'Prefiero ___ camisa blanca de aquí que esa negra de ahí.',
    translation: 'Я предпочитаю эту белую рубашку здесь, чем ту чёрную там.',
    distanceHint: '📍 Сравнение (здесь / de aquí)',
    options: ['esta', 'esa', 'aquella', 'este'],
    correctAnswer: 'esta',
    explanation: 'Слово «de aquí» однозначно указывает на дистанцию 1 (близко). «Camisa» — жен. род, поэтому ESTA.',
    exampleAudio: 'Prefiero esta camisa blanca de aquí que esa negra de ahí.',
  },
  {
    id: 20,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: 'No me des este plato, dame ___ que está junto a ti.',
    translation: 'Не давай мне эту тарелку, дай мне ту, что рядом с тобой.',
    distanceHint: '📍 Рядом с собеседником (junto a ti / ahí)',
    options: ['ese', 'este', 'aquel', 'eso'],
    correctAnswer: 'ese',
    explanation: '«Plato» — муж. род. «Junto a ti» (рядом с тобой) указывает на дистанцию 2 (ese/esa): ESE.',
    exampleAudio: 'No me des este plato, dame ese que está junto a ti.',
  },
  {
    id: 21,
    category: 'forms',
    distance: 'zone3_far',
    sentence: '¿Ves las dos casas? La verde de aquí es nueva, pero ___ del cerro es vieja.',
    translation: 'Видишь два дома? Зелёный здесь — новый, но вон тот на холме — старый.',
    distanceHint: '📍 Далеко на холме (del cerro / allá)',
    options: ['aquella', 'esta', 'esa', 'aquel'],
    correctAnswer: 'aquella',
    explanation: 'Речь идет о доме (casa — f.sg) вдалеке на холме: AQUELLA.',
    exampleAudio: '¿Ves las dos casas? La verde de aquí es nueva, pero aquella del cerro es vieja.',
  },
  {
    id: 22,
    category: 'neuter',
    distance: 'zone2_medium',
    sentence: '—Voy a renunciar a mi trabajo. —¡No digas ___!',
    translation: '—Я собираюсь уволиться с работы. —Не говори этого (такого)!',
    distanceHint: '📍 Ссылка на фразу собеседника (eso)',
    options: ['eso', 'esto', 'aquello', 'ese'],
    correctAnswer: 'eso',
    explanation: 'Ответ на слова собеседника: «¡No digas eso!» — не говори этого.',
    exampleAudio: 'No digas eso.',
  },
  {
    id: 23,
    category: 'adverbs',
    distance: 'zone1_close',
    sentence: 'Hace mucho frío ___, ven a sentarte cerca del fuego.',
    translation: 'Здесь очень холодно, иди садись ближе к огню.',
    distanceHint: '📍 Здесь (в этом месте / acá)',
    options: ['acá', 'ahí', 'allá', 'aquel'],
    correctAnswer: 'acá',
    explanation: '«Acá» / «aquí» обозначает место, где прямо сейчас находится говорящий.',
    exampleAudio: 'Hace mucho frío acá, ven a sentarte cerca del fuego.',
  },
  {
    id: 24,
    category: 'forms',
    distance: 'zone2_medium',
    sentence: 'Guarda ___ documentos que están en tu escritorio.',
    translation: 'Убери те документы, которые лежат на твоем письменном столе.',
    distanceHint: '📍 На твоем столе (у тебя / ahí)',
    options: ['esos', 'estos', 'aquellos', 'esas'],
    correctAnswer: 'esos',
    explanation: '«Documentos» — мужской род, множ. число. Находятся у собеседника: ESOS.',
    exampleAudio: 'Guarda esos documentos que están en tu escritorio.',
  },
  {
    id: 25,
    category: 'forms',
    distance: 'zone3_far',
    sentence: 'En ___ tiempos lejanos, la gente viajaba a caballo.',
    translation: 'В те далёкие времена люди путешествовали на лошадях.',
    distanceHint: '📍 Далекое прошлое (tiempos lejanos / aquellos)',
    options: ['aquellos', 'estos', 'esos', 'aquellas'],
    correctAnswer: 'aquellos',
    explanation: '«Tiempos» — муж. род мн. число. Для далёких исторических эпох: «en aquellos tiempos».',
    exampleAudio: 'En aquellos tiempos lejanos, la gente viajaba a caballo.',
  },
];
