services:
  hbbs:
    container_name: dev-migration-hbbs
    image: rustdesk-server:relayfix
    command: hbbs -r 145.239.82.124:21117
    environment:
      TEST_HBBS: "no"
      ALWAYS_USE_RELAY: "Y"
    volumes:
      - ./data:/root
    network_mode: host
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: dev-migration-hbbr
    image: rustdesk-server:relayfix
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
