# -*- coding: utf-8 -*-
"""
A1 Core Vocabulary Builder - 650 Essential Lemmas
Distributes exactly across 12 CEFR A1 domains according to specification.
"""
import json
import unicodedata
import re

def normalize_key(text):
    t = text.lower().strip()
    t = re.sub(r'^(el|la|los|las|un|una|unos|unas)\s+', '', t)
    t = re.sub(r'[¿?¡!.,;:«»"\'()]', '', t)
    return unicodedata.normalize('NFKD', t).encode('ASCII', 'ignore').decode('utf-8').strip()

DOMAINS_SPEC = {
    'identity': (45, 'a1-u01-first-contact'),
    'numbers-time': (55, 'a1-u06-calendar'),
    'people-family': (65, 'a1-u04-family'),
    'home-city': (65, 'a1-u08-home'),
    'food': (70, 'a1-u07-food'),
    'daily-actions': (75, 'a1-u05-actions'),
    'descriptions': (55, 'a1-u03-identity'),
    'clothes-shopping': (50, 'a1-u09-needs'),
    'transport-directions': (45, 'a1-u08-home'),
    'weather-leisure': (45, 'a1-u09-needs'),
    'function-words': (45, 'a1-u05-actions'),
    'survival-phrases': (35, 'a1-u01-first-contact'),
}

# 1. IDENTITY (45 lemmas) - unit: a1-u01-first-contact
identity_words = [
    ("nombre", "имя", "noun", "m", "nombre", "Mi nombre es Alejandro.", "Моё имя — Алехандро.", None),
    ("apellido", "фамилия", "noun", "m", "apellido", "¿Cuál es tu apellido?", "Какая у тебя фамилия?", None),
    ("edad", "возраст", "noun", "f", "edad", "¿Qué edad tienes?", "Сколько тебе лет?", None),
    ("país", "страна", "noun", "m", "país", "España es un país hermoso.", "Испания — красивая страна.", None),
    ("nacionalidad", "национальность", "noun", "f", "nacionalidad", "Mi nacionalidad es argentina.", "Моя национальность — аргентинка.", None),
    ("ciudad de origen", "родной город", "noun", "f", "ciudad de origen", "Mi ciudad de origen es Madrid.", "Мой родной город — Мадрид.", None),
    ("profesión", "профессия", "noun", "f", "profesión", "¿Cuál es tu profesión?", "Какая твоя профессия?", None),
    ("estudiante", "студент", "noun", "m", "estudiante", "Soy estudiante de español.", "Я студент, изучающий испанский.", "m/f"),
    ("profesor", "преподаватель", "noun", "m", "profesor", "El profesor explica la lección.", "Преподаватель объясняет урок.", None),
    ("médico", "врач", "noun", "m", "médico", "Mi hermano es médico.", "Мой брат — врач.", None),
    ("ingeniero", "инженер", "noun", "m", "ingeniero", "Trabajo como ingeniero.", "Я работаю инженером.", None),
    ("idioma", "язык", "noun", "m", "idioma", "El español es un idioma bonito.", "Испанский — красивый язык.", "Существительное мужского рода: el idioma"),
    ("lengua", "родной язык / речь", "noun", "f", "lengua", "Mi lengua materna es el ruso.", "Мой родной язык — русский.", None),
    ("español", "испанский язык / испанец", "noun", "m", "español", "Hablo un poco de español.", "Я немного говорю по-испански.", None),
    ("ruso", "русский язык / русский", "noun", "m", "ruso", "Ella habla ruso muy bien.", "Она очень хорошо говорит по-русски.", None),
    ("inglés", "английский язык", "noun", "m", "inglés", "Estudio inglés y español.", "Я учу английский и испанский.", None),
    ("pasaporte", "паспорт", "noun", "m", "pasaporte", "Aquí está mi pasaporte.", "Вот мой паспорт.", None),
    ("documento", "документ", "noun", "m", "documento", "Necesito un documento de identidad.", "Мне нужен документ, удостоверяющий личность.", None),
    ("firma", "подпись", "noun", "f", "firma", "Ponga su firma aquí, por favor.", "Поставьте вашу подпись здесь, пожалуйста.", None),
    ("dirección", "адрес", "noun", "f", "dirección", "¿Cuál es tu dirección?", "Какой у тебя адрес?", None),
    ("correo", "почта / email", "noun", "m", "correo", "Este es mi correo electrónico.", "Это моя электронная почта.", None),
    ("teléfono", "телефон", "noun", "m", "teléfono", "Mi número de teléfono es nuevo.", "Мой номер телефона новый.", None),
    ("número", "номер", "noun", "m", "número", "¿Qué número tienes?", "Какой у тебя номер?", None),
    ("contacto", "контакт", "noun", "m", "contacto", "Guarda mi contacto.", "Сохрани мой контакт.", None),
    ("tarjeta de identidad", "удостоверение личности", "noun", "f", "tarjeta de identidad", "Muestre su tarjeta de identidad.", "Покажите ваше удостоверение личности.", None),
    ("origen", "происхождение", "noun", "m", "origen", "¿Cuál es tu origen?", "Каково твоё происхождение?", None),
    ("extranjero", "иностранец", "noun", "m", "extranjero", "Soy extranjero en esta ciudad.", "Я иностранец в этом городе.", None),
    ("turista", "турист", "noun", "m", "turista", "Hay muchos turistas en Barcelona.", "В Барселоне много туристов.", "m/f"),
    ("guía", "гид / экскурсовод", "noun", "m", "guía", "El guía habla tres idiomas.", "Гид говорит на трёх языках.", "m/f"),
    ("vecino", "сосед", "noun", "m", "vecino", "Mi vecino es muy amable.", "Мой сосед очень приветливый.", None),
    ("compañero", "товарищ / одногруппник", "noun", "m", "compañero", "Es mi compañero de clase.", "Это мой одногруппник.", None),
    ("llamarse", "называться / зваться", "verb", None, "llamarse", "Me llamo Carlos.", "Меня зовут Карлос.", None),
    ("ser", "быть / являться", "verb", None, "ser", "Soy de Argentina.", "Я из Аргентины.", "Фундаментальный глагол сути и происхождения"),
    ("estar", "находиться / быть в состоянии", "verb", None, "estar", "Estoy muy bien hoy.", "Я отлично себя чувствую сегодня.", "Глагол состояния и местоположения"),
    ("vivir", "жить", "verb", None, "vivir", "Vivo en Madrid.", "Я живу в Мадриде.", None),
    ("hablar", "говорить", "verb", None, "hablar", "Hablo español e inglés.", "Я говорю по-испански и по-английски.", None),
    ("tener", "иметь", "verb", None, "tener", "Tengo veinticinco años.", "Мне 25 лет.", None),
    ("trabajar", "работать", "verb", None, "trabajar", "Trabajo en una oficina.", "Я работаю в офисе.", None),
    ("estudiar", "учиться", "verb", None, "estudiar", "Estudio en la universidad.", "Я учусь в университете.", None),
    ("presentar", "представлять / знакомить", "verb", None, "presentar", "Te presento a mi amigo.", "Познакомься с моим другом.", None),
    ("conocer", "знать / знакомиться", "verb", None, "conocer", "Mucho gusto en conocerte.", "Очень приятно познакомиться с тобой.", None),
    ("entender", "понимать", "verb", None, "entender", "Entiendo un poco de español.", "Я немного понимаю по-испански.", None),
    ("aprender", "учить / изучать", "verb", None, "aprender", "Quiero aprender español.", "Я хочу выучить испанский.", None),
    ("escribir", "писать", "verb", None, "escribir", "¿Cómo se escribe tu nombre?", "Как пишется твоё имя?", None),
    ("pronunciar", "произносить", "verb", None, "pronunciar", "¿Cómo se pronuncia esta palabra?", "Как произносится это слово?", None),
]

# 2. NUMBERS-TIME (55 lemmas) - unit: a1-u06-calendar
numbers_time_words = [
    ("cero", "ноль", "number", None, "cero", "El resultado es cero.", "Результат — ноль.", None),
    ("uno", "один", "number", None, "uno", "Tengo un billete.", "У меня один билет.", "un перед муж. родом"),
    ("dos", "два", "number", None, "dos", "Son las dos de la tarde.", "Сейчас два часа дня.", None),
    ("tres", "три", "number", None, "tres", "Hay tres personas aquí.", "Здесь три человека.", None),
    ("cuatro", "четыре", "number", None, "cuatro", "Tengo cuatro libros.", "У меня четыре книги.", None),
    ("cinco", "пять", "number", None, "cinco", "Son las cinco en punto.", "Сейчас ровно пять часов.", None),
    ("seis", "шесть", "number", None, "seis", "El tren sale a las seis.", "Поезд отправляется в шесть.", None),
    ("siete", "семь", "number", None, "siete", "La semana tiene siete días.", "В неделе семь дней.", None),
    ("ocho", "восемь", "number", None, "ocho", "Empiezo a trabajar a las ocho.", "Я начинаю работать в восемь.", None),
    ("nueve", "девять", "number", None, "nueve", "Son las nueve de la noche.", "Сейчас девять вечера.", None),
    ("diez", "десять", "number", None, "diez", "Cuesta diez euros.", "Это стоит десять евро.", None),
    ("once", "одиннадцать", "number", None, "once", "Son las once de la mañana.", "Сейчас одиннадцать утра.", None),
    ("doce", "двенадцать", "number", None, "doce", "Almorzamos a las doce.", "Мы обедаем в двенадцать.", None),
    ("trece", "тринадцать", "number", None, "trece", "Vivo en el número trece.", "Я живу в доме номер тринадцать.", None),
    ("catorce", "четырнадцать", "number", None, "catorce", "Tengo catorce días de vacaciones.", "У меня четырнадцать дней отпуска.", None),
    ("quince", "пятнадцать", "number", None, "quince", "Faltan quince minutos.", "Осталось пятнадцать минут.", None),
    ("dieciséis", "шестнадцать", "number", None, "dieciséis", "El billete cuesta dieciséis pesos.", "Билет стоит шестнадцать песо.", None),
    ("veinte", "двадцать", "number", None, "veinte", "Tengo veinte euros.", "У меня двадцать евро.", None),
    ("treinta", "тридцать", "number", None, "treinta", "El autobús llega en treinta minutos.", "Автобус приедет через тридцать минут.", None),
    ("cuarenta", "сорок", "number", None, "cuarenta", "El viaje dura cuarenta minutos.", "Поездка длится сорок минут.", None),
    ("cincuenta", "пятьдесят", "number", None, "cincuenta", "Son cincuenta dólares.", "Это пятьдесят долларов.", None),
    ("sesenta", "шестьдесят", "number", None, "sesenta", "Un minuto tiene sesenta segundos.", "В минуте шестьдесят секунд.", None),
    ("setenta", "семьдесят", "number", None, "setenta", "El libro tiene setenta páginas.", "В книге семьдесят страниц.", None),
    ("ochenta", "восемьдесят", "number", None, "ochenta", "El abuelo tiene ochenta años.", "Дедушке восемьдесят лет.", None),
    ("noventa", "девяносто", "number", None, "noventa", "Cuesta noventa pesos.", "Стоит девяносто песо.", None),
    ("cien", "сто", "number", None, "cien", "Hay cien personas en la sala.", "В зале сто человек.", "cien перед сущ., ciento uno"),
    ("quinientos", "пятьсот", "number", None, "quinientos", "La habitación cuesta quinientos pesos.", "Номер стоит пятьсот песо.", None),
    ("mil", "тысяча", "number", None, "mil", "Mil gracias por tu ayuda.", "Тысяча благодарностей за помощь.", None),
    ("primero", "первый", "adjective", "m", "primero", "Es mi primer viaje a España.", "Это моя первая поездка в Испанию.", "primer перед муж. родом"),
    ("segundo", "второй / секунда", "adjective", "m", "segundo", "Vivo en el segundo piso.", "Я живу на втором этаже.", None),
    ("tercero", "третий", "adjective", "m", "tercero", "El aula está en el tercer piso.", "Аудитория на третьем этаже.", "tercer перед муж. родом"),
    ("último", "последний", "adjective", "m", "último", "Es el último autobús de la noche.", "Это последний автобус за ночь.", None),
    ("hora", "час / время", "noun", "f", "hora", "¿Qué hora es?", "Который час?", None),
    ("minuto", "минута", "noun", "m", "minuto", "Espere un minuto, por favor.", "Подождите минуту, пожалуйста.", None),
    ("segundo (tiempo)", "секунда", "noun", "m", "segundo (tiempo)", "Un momento dura pocos segundos.", "Момент длится несколько секунд.", None),
    ("cuarto de hora", "четверть часа", "noun", "m", "cuarto de hora", "Son las tres y cuarto.", "Сейчас четверть четвёртого (3:15).", None),
    ("media hora", "полчаса", "noun", "f", "media hora", "Son las cuatro y media.", "Сейчас половина пятого (4:30).", None),
    ("mediodía", "полдень", "noun", "m", "mediodía", "Almorzamos al mediodía.", "Мы обедаем в полдень.", None),
    ("medianoche", "полночь", "noun", "f", "medianoche", "Regreso antes de medianoche.", "Я вернусь до полуночи.", None),
    ("en punto", "ровно (по часам)", "phrase", None, "en punto", "La clase empieza a las nueve en punto.", "Урок начинается ровно в девять.", None),
    ("mañana (tiempo)", "утро", "noun", "f", "mañana (tiempo)", "Por la mañana tomo café.", "По утрам я пью кофе.", None),
    ("tarde (tiempo)", "день / вторая половина дня", "noun", "f", "tarde (tiempo)", "Por la tarde estudio español.", "Днём я учу испанский.", None),
    ("noche", "ночь / вечер", "noun", "f", "noche", "Buenas noches a todos.", "Доброй ночи всем.", None),
    ("día", "день", "noun", "m", "día", "Hoy es un buen día.", "Сегодня хороший день.", "Существительное мужского рода: el día"),
    ("semana", "неделя", "noun", "f", "semana", "La próxima semana viajo a Madrid.", "На следующей неделе я еду в Мадрид.", None),
    ("fin de semana", "выходные", "noun", "m", "fin de semana", "¿Qué haces el fin de semana?", "Что ты делаешь на выходных?", None),
    ("mes", "месяц", "noun", "m", "mes", "Febrero es un mes corto.", "Февраль — короткий месяц.", None),
    ("año", "год", "noun", "m", "año", "Tengo un año aprendiendo español.", "Я уже год учу испанский.", None),
    ("lunes", "понедельник", "noun", "m", "lunes", "El lunes tengo examen.", "В понедельник у меня экзамен.", "el lunes / los lunes"),
    ("martes", "вторник", "noun", "m", "martes", "Nos vemos el martes.", "Увидимся во вторник.", None),
    ("miércoles", "среда", "noun", "m", "miércoles", "El miércoles juego fútbol.", "В среду я играю в футбол.", None),
    ("jueves", "четверг", "noun", "m", "jueves", "El jueves ceno con amigos.", "В четверг я ужинаю с друзьями.", None),
    ("viernes", "пятница", "noun", "m", "viernes", "¡Por fin es viernes!", "Наконец-то пятница!", None),
    ("sábado", "суббота", "noun", "m", "sábado", "El sábado voy al mercado.", "В субботу я иду на рынок.", None),
    ("domingo", "воскресенье", "noun", "m", "domingo", "El domingo descanso con la familia.", "В воскресенье я отдыхаю с семьёй.", None),
]

# 3. PEOPLE-FAMILY (65 lemmas) - unit: a1-u04-family
people_family_words = [
    ("familia", "семья", "noun", "f", "familia", "Tengo una familia grande.", "У меня большая семья.", None),
    ("padre", "отец", "noun", "m", "padre", "Mi padre trabaja en un banco.", "Мой отец работает в банке.", None),
    ("madre", "мать", "noun", "f", "madre", "Mi madre es profesora.", "Моя мама — учительница.", None),
    ("papá", "папа", "noun", "m", "papá", "Mi papá cocina muy bien.", "Мой папа отлично готовит.", None),
    ("mamá", "мама", "noun", "f", "mamá", "Mi mamá lee mucho.", "Моя мама много читает.", None),
    ("hijo", "сын", "noun", "m", "hijo", "Mi hijo tiene ocho años.", "Моему сыну восемь лет.", None),
    ("hija", "дочь", "noun", "f", "hija", "Mi hija estudia música.", "Моя дочь учит музыку.", None),
    ("hermano", "брат", "noun", "m", "hermano", "Tengo un hermano mayor.", "У меня есть старший брат.", None),
    ("hermana", "сестра", "noun", "f", "hermana", "Mi hermana vive en Sevilla.", "Моя сестра живёт в Севилье.", None),
    ("abuelo", "дедушка", "noun", "m", "abuelo", "Mi abuelo cuenta historias bonitas.", "Мой дедушка рассказывает красивые истории.", None),
    ("abuela", "бабушка", "noun", "f", "abuela", "Mi abuela prepara pasteles ricos.", "Моя бабушка готовит вкусные пироги.", None),
    ("tío", "дядя", "noun", "m", "tío", "Mi tío vive en Valencia.", "Мой дядя живёт в Валенсии.", None),
    ("tía", "тётя", "noun", "f", "tía", "Mi tía es doctora.", "Моя тётя — врач.", None),
    ("primo", "двоюродный брат", "noun", "m", "primo", "Juego con mi primo los domingos.", "Я играю с кузеном по воскресеньям.", None),
    ("prima", "двоюродная сестра", "noun", "f", "prima", "Mi prima habla francés.", "Моя кузина говорит по-французски.", None),
    ("sobrino", "племянник", "noun", "m", "sobrino", "Mi sobrino empieza la escuela.", "Мой племянник идёт в школу.", None),
    ("sobrina", "племянница", "noun", "f", "sobrina", "Mi sobrina dibuja muy bien.", "Моя племянница отлично рисует.", None),
    ("nieto", "внук", "noun", "m", "nieto", "El abuelo pasea con su nieto.", "Дедушка гуляет со своим внуком.", None),
    ("nieta", "внучка", "noun", "f", "nieta", "Mi nieta tiene tres años.", "Моей внучке три года.", None),
    ("esposo", "муж / супруг", "noun", "m", "esposo", "Mi esposo es arquitecto.", "Мой муж — архитектор.", None),
    ("esposa", "жена / супруга", "noun", "f", "esposa", "Mi esposa es abogada.", "Моя жена — юрист.", None),
    ("marido", "муж", "noun", "m", "marido", "Mi marido está en el trabajo.", "Мой муж на работе.", None),
    ("mujer (esposa)", "женщина / жена", "noun", "f", "mujer (esposa)", "Ella es una mujer inteligente.", "Она умная женщина.", None),
    ("novio", "парень / жених", "noun", "m", "novio", "Mi novio es muy simpático.", "Мой парень очень приятный.", None),
    ("novia", "девушка / невеста", "noun", "f", "novia", "Mi novia vive cerca de aquí.", "Моя девушка живёт рядом отсюда.", None),
    ("padres", "родители", "noun", "m", "padres", "Mis padres viven en el campo.", "Мои родители живут за городом.", None),
    ("pariente", "родственник", "noun", "m", "pariente", "Tengo parientes en México.", "У меня есть родственники в Мексике.", None),
    ("persona", "человек", "noun", "f", "persona", "Es una buena persona.", "Это хороший человек.", None),
    ("gente", "люди / народ", "noun", "f", "gente", "Hay mucha gente en la calle.", "На улице много людей.", "Всегда ед. число: la gente es..."),
    ("hombre", "мужчина", "noun", "m", "hombre", "Aquel hombre es el director.", "Вон тот мужчина — директор.", None),
    ("chico", "парень / мальчик", "noun", "m", "chico", "Es un chico muy amable.", "Это очень приветливый парень.", None),
    ("chica", "девушка / девочка", "noun", "f", "chica", "Esa chica habla español.", "Эта девушка говорит по-испански.", None),
    ("niño", "ребёнок / мальчик", "noun", "m", "niño", "El niño juega en el parque.", "Ребёнок играет в парке.", None),
    ("niña", "девочка", "noun", "f", "niña", "La niña lee un cuento.", "Девочка читает сказку.", None),
    ("bebé", "малыш / младенец", "noun", "m", "bebé", "El bebé duerme tranquilamente.", "Малыш спокойно спит.", None),
    ("amigo", "друг", "noun", "m", "amigo", "Juan es mi mejor amigo.", "Хуан — мой лучший друг.", None),
    ("amiga", "подруга", "noun", "f", "amiga", "Laura es mi amiga de la infancia.", "Лаура — моя подруга детства.", None),
    ("señor", "господин / сеньор", "noun", "m", "señor", "Buenos días, señor García.", "Доброе утро, сеньор Гарсия.", None),
    ("señora", "госпожа / сеньора", "noun", "f", "señora", "Pase usted, señora.", "Проходите, сеньора.", None),
    ("señorita", "девушка / сеньорита", "noun", "f", "señorita", "La señorita es recepcionista.", "Эта девушка — администратор.", None),
    ("cuerpo", "тело", "noun", "m", "cuerpo", "El ejercicio es bueno para el cuerpo.", "Упражнения полезны для тела.", None),
    ("cabeza", "голова", "noun", "f", "cabeza", "Me duele la cabeza.", "У меня болит голова.", None),
    ("cara", "лицо", "noun", "f", "cara", "Tiene una cara sonriente.", "У неё улыбчивое лицо.", None),
    ("ojo", "глаз", "noun", "m", "ojo", "Tiene los ojos marrones.", "У него карие глаза.", None),
    ("nariz", "нос", "noun", "f", "nariz", "Respira por la nariz.", "Дыши через нос.", None),
    ("boca", "рот", "noun", "f", "boca", "Abre la boca, por favor.", "Откройте рот, пожалуйста.", None),
    ("oreja", "ухо (раковина)", "noun", "f", "oreja", "Tengo frío en las orejas.", "У меня замёрзли уши.", None),
    ("diente", "зуб", "noun", "m", "diente", "Me cepillo los dientes.", "Я чищу зубы.", None),
    ("lengua (cuerpo)", "язык (орган)", "noun", "f", "lengua (cuerpo)", "Muestra la lengua al médico.", "Покажи язык врачу.", None),
    ("pelo", "волосы", "noun", "m", "pelo", "Tiene el pelo largo y negro.", "У неё длинные чёрные волосы.", None),
    ("cabello", "волосы (литературное)", "noun", "m", "cabello", "Su cabello es rubio.", "Её волосы светлые.", None),
    ("cuello", "шея", "noun", "m", "cuello", "Lleva una bufanda en el cuello.", "Он носит шарф на шее.", None),
    ("hombro", "плечо", "noun", "m", "hombro", "Me duele el hombro derecho.", "У меня болит правое плечо.", None),
    ("brazo", "рука (от плеча)", "noun", "m", "brazo", "Levanta el brazo.", "Подними руку.", None),
    ("mano", "рука (кисть)", "noun", "f", "mano", "Lávate las manos antes de comer.", "Помой руки перед едой.", "Женский род: la mano"),
    ("dedo", "палец", "noun", "m", "dedo", "Tengo cinco dedos en la mano.", "У меня пять пальцев на руке.", None),
    ("pecho", "грудь", "noun", "m", "pecho", "Siento opresión en el pecho.", "Я чувствую тяжесть в груди.", None),
    ("espalda", "спина", "noun", "f", "espalda", "Tengo dolor de espalda.", "У меня боль в спине.", None),
    ("estómago", "желудок / живот", "noun", "m", "estómago", "Tengo hambre en el estómago.", "У меня урчит в животе.", None),
    ("barriga", "живот (разговорное)", "noun", "f", "barriga", "Me duele la barriga.", "У меня болит живот.", None),
    ("pierna", "нога (выше ступни)", "noun", "f", "pierna", "Tengo las piernas cansadas.", "У меня устали ноги.", None),
    ("rodilla", "колено", "noun", "f", "rodilla", "Me lastimé la rodilla jugando.", "Я ушиб колено во время игры.", None),
    ("pie", "нога (стопа)", "noun", "m", "pie", "Voy a pie al trabajo.", "Я иду пешком на работу.", None),
    ("corazón", "сердце", "noun", "m", "corazón", "El corazón late con fuerza.", "Сердце бьётся сильно.", None),
    ("piel", "кожа", "noun", "f", "piel", "Protege tu piel del sol.", "Защищай свою кожу от солнца.", None),
]

# 4. HOME-CITY (65 lemmas) - unit: a1-u08-home
home_city_words = [
    ("casa", "дом", "noun", "f", "casa", "Mi casa es pequeña y luminosa.", "Мой дом маленький и светлый.", None),
    ("apartamento", "квартира", "noun", "m", "apartamento", "Alquilo un apartamento céntrico.", "Я снимаю квартиру в центре.", None),
    ("piso", "квартира / этаж", "noun", "m", "piso", "Vivo en el tercer piso.", "Я живу на третьем этаже.", "В Испании piso = квартира"),
    ("habitación", "комната", "noun", "f", "habitación", "Mi habitación tiene balcón.", "В моей комнате есть балкон.", None),
    ("dormitorio", "спальня", "noun", "m", "dormitorio", "El dormitorio es muy tranquilo.", "Спальня очень тихая.", None),
    ("cocina", "кухня", "noun", "f", "cocina", "Cocino la cena en la cocina.", "Я готовлю ужин на кухне.", None),
    ("baño", "ванная комната / туалет", "noun", "m", "baño", "¿Dónde está el baño?", "Где находится туалет?", None),
    ("salón", "гостиная", "noun", "m", "salón", "Descansamos en el salón.", "Мы отдыхаем в гостиной.", None),
    ("comedor", "столовая", "noun", "m", "comedor", "La mesa del comedor es de madera.", "Стол в столовой деревянный.", None),
    ("terraza", "терраса", "noun", "f", "terraza", "Tomamos café en la terraza.", "Мы пьём кофе на террасе.", None),
    ("balcón", "балкон", "noun", "m", "balcón", "Hay flores en el balcón.", "На балконе цветы.", None),
    ("jardín", "сад", "noun", "m", "jardín", "Los niños juegan en el jardín.", "Дети играют в саду.", None),
    ("patio", "внутренний дворик / патио", "noun", "m", "patio", "El patio tiene muchas plantas.", "В дворике много растений.", None),
    ("garaje", "гараж", "noun", "m", "garaje", "El coche está en el garaje.", "Машина в гараже.", None),
    ("entrada", "вход / прихожая", "noun", "f", "entrada", "Deja los zapatos en la entrada.", "Оставь обувь у входа.", None),
    ("pasillo", "коридор", "noun", "m", "pasillo", "El baño está al final del pasillo.", "Ванная в конце коридора.", None),
    ("puerta", "дверь", "noun", "f", "puerta", "Cierra la puerta, por favor.", "Закрой дверь, пожалуйста.", None),
    ("ventana", "окно", "noun", "f", "ventana", "Abre la ventana para ventilar.", "Открой окно, чтобы проветрить.", None),
    ("pared", "стена", "noun", "f", "pared", "Hay un cuadro en la pared.", "На стене висит картина.", None),
    ("suelo", "пол", "noun", "m", "suelo", "El suelo está muy limpio.", "Пол очень чистый.", None),
    ("techo", "потолок / крыша", "noun", "m", "techo", "La lámpara cuelga del techo.", "Лампа свисает с потолка.", None),
    ("mesa", "стол", "noun", "f", "mesa", "El libro está sobre la mesa.", "Книга лежит на столе.", None),
    ("silla", "стул", "noun", "f", "silla", "Siéntate en esta silla.", "Садись на этот стул.", None),
    ("cama", "кровать", "noun", "f", "cama", "La cama es muy cómoda.", "Кровать очень удобная.", None),
    ("sofá", "диван", "noun", "m", "sofá", "Me siento en el sofá a leer.", "Я сажусь на диван читать.", "Мужской род: el sofá"),
    ("sillón", "кресло", "noun", "m", "sillón", "El abuelo duerme en el sillón.", "Дедушка спит в кресле.", None),
    ("armario", "шкаф", "noun", "m", "armario", "Guardo la ropa en el armario.", "Я храню одежду в шкафу.", None),
    ("estante", "полка", "noun", "m", "estante", "Los libros están en el estante.", "Книги стоят на полке.", None),
    ("lámpara", "лампа", "noun", "f", "lámpara", "Enciende la lámpara, por favor.", "Включи лампу, пожалуйста.", None),
    ("espejo", "зеркало", "noun", "m", "espejo", "Me miro en el espejo.", "Я смотрю на себя в зеркало.", None),
    ("nevera", "холодильник", "noun", "f", "nevera", "La leche está en la nevera.", "Молоко в холодильнике.", "В Лат. Америке: refrigerador/heladera"),
    ("lavadora", "стиральная машина", "noun", "f", "lavadora", "Pongo la ropa en la lavadora.", "Я кладу одежду в стиральную машину.", None),
    ("ciudad", "город", "noun", "f", "ciudad", "Madrid es una gran ciudad.", "Мадрид — большой город.", None),
    ("pueblo", "посёлок / деревня / народ", "noun", "m", "pueblo", "Mis abuelos viven en un pueblo.", "Мои бабушка и дедушка живут в посёлке.", None),
    ("calle", "улица", "noun", "f", "calle", "Camino por la calle principal.", "Я иду по главной улице.", None),
    ("avenida", "проспект / авенида", "noun", "f", "avenida", "El banco está en la avenida.", "Банк находится на проспекте.", None),
    ("plaza", "площадь", "noun", "f", "plaza", "Quedamos en la plaza mayor.", "Мы встретимся на главной площади.", None),
    ("parque", "парк", "noun", "m", "parque", "Paseo por el parque cada tarde.", "Я гуляю по парку каждый вечер.", None),
    ("barrio", "район / квартал", "noun", "m", "barrio", "Vivo en un barrio tranquilo.", "Я живу в тихом районе.", None),
    ("centro", "центр города", "noun", "m", "centro", "El hotel está en el centro.", "Отель находится в центре.", None),
    ("edificio", "здание", "noun", "m", "edificio", "Es un edificio moderno.", "Это современное здание.", None),
    ("museo", "музей", "noun", "m", "museo", "Visito el museo de arte.", "Я посещаю художественный музей.", None),
    ("teatro", "театр", "noun", "m", "teatro", "Vamos al teatro esta noche.", "Мы идём в театр сегодня вечером.", None),
    ("cine", "кинотеатр / кино", "noun", "m", "cine", "Me gusta ir al cine los viernes.", "Мне нравится ходить в кино по пятницам.", None),
    ("hotel", "отель / гостиница", "noun", "m", "hotel", "Reservé una habitación en el hotel.", "Я забронировал номер в отеле.", None),
    ("banco (lugar)", "банк", "noun", "m", "banco (lugar)", "Cambio dinero en el banco.", "Я меняю деньги в банке.", None),
    ("hospital", "больница", "noun", "m", "hospital", "El médico trabaja en el hospital.", "Врач работает в больнице.", None),
    ("farmacia", "аптека", "noun", "f", "farmacia", "Compro medicina en la farmacia.", "Я покупаю лекарство в аптеке.", None),
    ("supermercado", "супермаркет", "noun", "m", "supermercado", "Hago las compras en el supermercado.", "Я делаю покупки в супермаркете.", None),
    ("mercado", "рынок", "noun", "m", "mercado", "Compro fruta fresca en el mercado.", "Я покупаю свежие фрукты на рынке.", None),
    ("tienda", "магазин", "noun", "f", "tienda", "La tienda abre a las diez.", "Магазин открывается в десять.", None),
    ("panadería", "булочная / пекарня", "noun", "f", "panadería", "Compro pan caliente en la panadería.", "Я покупаю горячий хлеб в булочной.", None),
    ("restaurante", "ресторан", "noun", "m", "restaurante", "Cenamos en un restaurante típico.", "Мы ужинаем в традиционном ресторане.", None),
    ("cafetería", "кафе", "noun", "f", "cafetería", "Tomamos un cortado en la cafetería.", "Мы пьём кортадо в кафе.", None),
    ("bar", "бар", "noun", "m", "bar", "Nos encontramos en el bar.", "Мы встретимся в баре.", None),
    ("escuela", "школа", "noun", "f", "escuela", "Los niños van a la escuela.", "Дети идут в школу.", None),
    ("colegio", "колледж / школа", "noun", "m", "colegio", "El colegio está cerca de casa.", "Школа находится близко к дому.", None),
    ("universidad", "университет", "noun", "f", "universidad", "Estudio en la universidad.", "Я учусь в университете.", None),
    ("biblioteca", "библиотека", "noun", "f", "biblioteca", "Estudio en silencio en la biblioteca.", "Я занимаюсь в тишине в библиотеке.", None),
    ("oficina", "офис", "noun", "f", "oficina", "Trabajo en una oficina moderna.", "Я работаю в современном офисе.", None),
    ("correos", "почтовое отделение", "noun", "m", "correos", "Envío una carta en correos.", "Я отправляю письмо на почте.", None),
    ("iglesia", "церковь", "noun", "f", "iglesia", "La iglesia antigua está en la plaza.", "Старинная церковь стоит на площади.", None),
    ("estación", "станция / вокзал", "noun", "f", "estación", "El tren llega a la estación.", "Поезд прибывает на вокзал.", None),
    ("puente", "мост", "noun", "m", "puente", "Cruzamos el puente a pie.", "Мы переходим мост пешком.", None),
    ("playa", "пляж", "noun", "f", "playa", "En verano vamos a la playa.", "Летом мы ходим на пляж.", None),
]

# 5. FOOD (70 lemmas) - unit: a1-u07-food
food_words = [
    ("comida", "еда / обед", "noun", "f", "comida", "La comida española es deliciosa.", "Испанская еда восхитительна.", None),
    ("bebida", "напиток", "noun", "f", "bebida", "¿Qué bebida prefieres?", "Какой напиток ты предпочитаешь?", None),
    ("agua", "вода", "noun", "f", "agua", "Bebo un vaso de agua fría.", "Я пью стакан холодной воды.", "el agua (жен. род с ударным а-)"),
    ("leche", "молоко", "noun", "f", "leche", "Tomo café con leche por la mañana.", "Я пью кофе с молоком по утрам.", None),
    ("café", "кофе", "noun", "m", "café", "Un café solo, por favor.", "Один черный кофе, пожалуйста.", None),
    ("té", "чай", "noun", "m", "té", "Prefiero té verde con limón.", "Я предпочитаю зеленый чай с лимоном.", None),
    ("zumo", "сок", "noun", "m", "zumo", "Quiero un zumo de naranja natural.", "Я хочу натуральный апельсиновый сок.", "В Лат. Америке: jugo"),
    ("vino", "вино", "noun", "m", "vino", "Una copa de vino tinto, por favor.", "Бокал красного вина, пожалуйста.", None),
    ("cerveza", "пиво", "noun", "f", "cerveza", "Una cerveza bien fría, por favor.", "Очень холодное пиво, пожалуйста.", None),
    ("refresco", "газировка", "noun", "m", "refresco", "No bebo refrescos con azúcar.", "Я не пью газировку с сахаром.", None),
    ("pan", "хлеб", "noun", "m", "pan", "Compro pan fresco cada día.", "Я покупаю свежий хлеб каждый день.", None),
    ("queso", "сыр", "noun", "m", "queso", "Me gusta el queso manchego.", "Мне нравится сыр манчего.", None),
    ("mantequilla", "сливочное масло", "noun", "f", "mantequilla", "Pongo mantequilla en la tostada.", "Я мажу масло на тост.", None),
    ("aceite", "растительное масло", "noun", "m", "aceite", "Uso aceite de oliva virgen.", "Я использую оливковое масло.", None),
    ("sal", "соль", "noun", "f", "sal", "¿Me pasas la sal, por favor?", "Передашь мне соль, пожалуйста?", None),
    ("pimienta", "перец (приправа)", "noun", "f", "pimienta", "Añado un poco de pimienta.", "Я добавляю немного перца.", None),
    ("azúcar", "сахар", "noun", "m", "azúcar", "¿Tomas café con azúcar?", "Ты пьёшь кофе с сахаром?", None),
    ("carne", "мясо", "noun", "f", "carne", "Prefiero carne a la brasa.", "Я предпочитаю мясо на гриле.", None),
    ("pollo", "курица", "noun", "m", "pollo", "Hoy cocino arroz con pollo.", "Сегодня я готовлю рис с курицей.", None),
    ("pescado", "рыба (приготовленная)", "noun", "m", "pescado", "El pescado está muy fresco.", "Рыба очень свежая.", None),
    ("pez", "рыба (живая)", "noun", "m", "pez", "Hay peces de colores en el acuario.", "В аквариуме разноцветные рыбки.", None),
    ("huevo", "яйцо", "noun", "m", "huevo", "Desayuno dos huevos fritos.", "Я завтракаю двумя жареными яйцами.", None),
    ("arroz", "рис", "noun", "m", "arroz", "La paella lleva arroz y azafrán.", "В паэлью кладут рис и шафран.", None),
    ("pasta", "макароны / паста", "noun", "f", "pasta", "Cocino pasta con tomate.", "Я готовлю пасту с томатом.", None),
    ("sopa", "суп", "noun", "f", "sopa", "La sopa caliente es reconfortante.", "Горячий суп согревает.", None),
    ("ensalada", "салат", "noun", "f", "ensalada", "Pido una ensalada mixta.", "Я заказываю смешанный салат.", None),
    ("fruta", "фрукты / фрукт", "noun", "f", "fruta", "Como fruta todos los días.", "Я ем фрукты каждый день.", None),
    ("manzana", "яблоко", "noun", "f", "manzana", "Una manzana roja y dulce.", "Красное сладкое яблоко.", None),
    ("plátano", "банан", "noun", "m", "plátano", "Como un plátano antes de entrenar.", "Я ем банан перед тренировкой.", "В Лат. Америке: banana"),
    ("naranja", "апельсин", "noun", "f", "naranja", "Las naranjas de Valencia son famosas.", "Апельсины из Валенсии знамениты.", None),
    ("limón", "лимон", "noun", "m", "limón", "Pongo limón en el té.", "Я кладу лимон в чай.", None),
    ("fresa", "клубника", "noun", "f", "fresa", "Me encantan las fresas con nata.", "Обожаю клубнику со сливками.", "В Аргентине: frutilla"),
    ("uva", "виноград / виноградина", "noun", "f", "uva", "En Nochevieja comemos doce uvas.", "В новогоднюю ночь мы едим 12 виноградин.", None),
    ("verdura", "овощи / зелень", "noun", "f", "verdura", "Compro verdura fresca en la tienda.", "Я покупаю свежие овощи в магазине.", None),
    ("patata", "картофель", "noun", "f", "patata", "Hago una tortilla de patatas.", "Я делаю картофельную тортилью.", "В Лат. Америке: papa"),
    ("tomate", "помидор", "noun", "m", "tomate", "La ensalada lleva tomate y cebolla.", "В салате помидоры и лук.", None),
    ("cebolla", "лук", "noun", "f", "cebolla", "Pico la cebolla muy fina.", "Я мелко режу лук.", None),
    ("ajo", "чеснок", "noun", "m", "ajo", "El pan con ajo está delicioso.", "Хлеб с чесноком очень вкусный.", None),
    ("zanahoria", "морковь", "noun", "f", "zanahoria", "La zanahoria tiene vitamina A.", "В моркови есть витамин А.", None),
    ("lechuga", "салат-латук / листья салата", "noun", "f", "lechuga", "Lavo la lechuga para la cena.", "Я мою салат к ужину.", None),
    ("jamón", "ветчина / хамон", "noun", "m", "jamón", "Un bocadillo de jamón serrano.", "Бутерброд с серрано.", None),
    ("bocadillo", "сэндвич / бутерброд", "noun", "m", "bocadillo", "Como un bocadillo a media mañana.", "Я съедаю бутерброд в полдень.", "В Лат. Америке: sándwich/torta"),
    ("tapa", "тапас / закуска", "noun", "f", "tapa", "Vamos a tomar unas tapas al bar.", "Пойдём перекусим тапас в баре.", None),
    ("tortilla", "испанский омлет / тортилья", "noun", "f", "tortilla", "La tortilla española lleva patatas.", "В испанскую тортилью кладут картофель.", None),
    ("pizza", "пицца", "noun", "f", "pizza", "Pedimos una pizza de queso.", "Мы заказываем сырную пиццу.", None),
    ("hamburguesa", "гамбургер", "noun", "f", "hamburguesa", "Quiero una hamburguesa con patatas.", "Я хочу бургер с картошкой.", None),
    ("postre", "десерт", "noun", "m", "postre", "¿Qué tienen de postre hoy?", "Что у вас сегодня на десерт?", None),
    ("helado", "мороженое", "noun", "m", "helado", "Un helado de chocolate, por favor.", "Шоколадное мороженое, пожалуйста.", None),
    ("chocolate", "шоколад", "noun", "m", "chocolate", "Me gusta el chocolate negro.", "Мне нравится тёмный шоколад.", None),
    ("tarta", "торт / пирог", "noun", "f", "tarta", "Una porción de tarta de manzana.", "Кусочек яблочного пирога.", None),
    ("galleta", "печенье", "noun", "f", "galleta", "Tomo galletas con el café.", "Я ем печенье с кофе.", None),
    ("desayuno", "завтрак", "noun", "m", "desayuno", "El desayuno está incluido en el hotel.", "Завтрак включён в отель.", None),
    ("almuerzo", "обед", "noun", "m", "almuerzo", "El almuerzo es a las dos de la tarde.", "Обед в два часа дня.", None),
    ("cena", "ужин", "noun", "f", "cena", "La cena en España es tarde.", "Ужин в Испании поздний.", None),
    ("menú", "меню", "noun", "m", "menú", "¿Podemos ver el menú del día?", "Можем ли мы посмотреть меню дня?", None),
    ("carta", "меню a la carte", "noun", "f", "carta", "Tráiganos la carta, por favor.", "Принесите нам меню, пожалуйста.", None),
    ("cuenta", "счёт (в ресторане)", "noun", "f", "cuenta", "La cuenta, por favor.", "Счёт, пожалуйста.", None),
    ("camarero", "официант", "noun", "m", "camarero", "El camarero es muy atento.", "Официант очень внимательный.", "В Лат. Америке: mesero/mozo"),
    ("propina", "чаевые", "noun", "f", "propina", "Dejamos una buena propina.", "Мы оставляем хорошие чаевые.", None),
    ("vaso", "стакан", "noun", "m", "vaso", "Un vaso de agua, por favor.", "Стакан воды, пожалуйста.", None),
    ("copa", "бокал", "noun", "f", "copa", "Una copa de vino blanco.", "Бокал белого вина.", None),
    ("taza", "чашка", "noun", "f", "taza", "Una taza de té caliente.", "Чашка горячего чая.", None),
    ("plato", "тарелка / блюдо", "noun", "m", "plato", "El primer plato es sopa.", "Первое блюдо — суп.", None),
    ("tenedor", "вилка", "noun", "m", "tenedor", "Necesito un tenedor limpio.", "Мне нужна чистая вилка.", None),
    ("cuchillo", "нож", "noun", "m", "cuchillo", "Este cuchillo no corta bien.", "Этот нож плохо режет.", None),
    ("cuchara", "ложка", "noun", "f", "cuchara", "Tomo la sopa con cuchara.", "Я ем суп ложкой.", None),
    ("servilleta", "салфетка", "noun", "f", "servilleta", "¿Tiene otra servilleta?", "У вас есть ещё салфетка?", None),
    ("botella", "бутылка", "noun", "f", "botella", "Una botella de agua mineral sin gas.", "Бутылка минеральной воды без газа.", None),
    ("delicioso", "вкусный / восхитительный", "adjective", "m", "delicioso", "El plato está delicioso.", "Блюдо восхитительное.", None),
    ("rico", "вкусный / богатый", "adjective", "m", "rico", "¡Qué rico está todo!", "Как всё вкусно!", None),
]

# 6. DAILY-ACTIONS (75 lemmas) - unit: a1-u05-actions
daily_actions_words = [
    ("levantarse", "вставать (с постели)", "verb", None, "levantarse", "Me levanto a las siete de la mañana.", "Я встаю в семь утра.", None),
    ("despertarse", "просыпаться", "verb", None, "despertarse", "Me despierto temprano todos los días.", "Я просыпаюсь рано каждый день.", None),
    ("ducharse", "принимать душ", "verb", None, "ducharse", "Me ducho con agua caliente.", "Я принимаю горячий душ.", None),
    ("lavarse", "умываться / мыться", "verb", None, "lavarse", "Me lavo la cara por la mañana.", "Я умываю лицо по утрам.", None),
    ("cepillarse", "чистить (зубы)", "verb", None, "cepillarse", "Me cepillo los dientes después de comer.", "Я чищу зубы после еды.", None),
    ("peinarse", "причёсываться", "verb", None, "peinarse", "Me peino delante del espejo.", "Я причесываюсь перед зеркалом.", None),
    ("vestirse", "одеваться", "verb", None, "vestirse", "Me visto rápido para no llegar tarde.", "Я быстро одеваюсь, чтобы не опоздать.", None),
    ("desayunar", "завтракать", "verb", None, "desayunar", "Desayuno café y tostadas.", "Я завтракаю кофе и тостами.", None),
    ("almorzar", "обедать", "verb", None, "almorzar", "Almuerzo con mis compañeros de trabajo.", "Я обедаю с коллегами по работе.", None),
    ("cenar", "ужинать", "verb", None, "cenar", "Cenamos en familia a las nueve.", "Мы ужинаем всей семьей в девять.", None),
    ("salir", "выходить / уходить", "verb", None, "salir", "Salgo de casa a las ocho.", "Я выхожу из дома в восемь.", None),
    ("entrar", "входить", "verb", None, "entrar", "Entro en la oficina a tiempo.", "Я захожу в офис вовремя.", None),
    ("llegar", "прибывать / приходить", "verb", None, "llegar", "El tren llega a las diez.", "Поезд прибывает в десять.", None),
    ("volver", "возвращаться", "verb", None, "volver", "Vuelvo a casa por la tarde.", "Я возвращаюсь домой днём.", None),
    ("regresar", "возвращаться (синоним)", "verb", None, "regresar", "Regreso el próximo mes.", "Я возвращаюсь в следующем месяце.", None),
    ("ir", "идти / ехать", "verb", None, "ir", "Voy al gimnasio los lunes.", "Я хожу в спортзал по понедельникам.", None),
    ("venir", "приходить / приезжать", "verb", None, "venir", "¿Vienes a la fiesta esta noche?", "Ты придёшь на вечеринку сегодня?", None),
    ("caminar", "ходить пешком / гулять", "verb", None, "caminar", "Camino treinta minutos al día.", "Я хожу пешком тридцать минут в день.", None),
    ("correr", "бегать", "verb", None, "correr", "Corro por el parque por las mañanas.", "Я бегаю по парку по утрам.", None),
    ("viajar", "путешествовать", "verb", None, "viajar", "Me gusta viajar en tren.", "Мне нравится путешествовать на поезде.", None),
    ("descansar", "отдыхать", "verb", None, "descansar", "Descanso los fines de semana.", "Я отдыхаю по выходным.", None),
    ("dormir", "спать", "verb", None, "dormir", "Duermo ocho horas cada noche.", "Я сплю восемь часов каждую ночь.", None),
    ("acostarse", "ложиться спать", "verb", None, "acostarse", "Me acuesto a las once de la noche.", "Я ложусь спать в одиннадцать ночи.", None),
    ("hacer", "делать", "verb", None, "hacer", "Hago la tarea de español.", "Я делаю домашнее задание по испанскому.", None),
    ("poder", "мочь / иметь возможность", "verb", None, "poder", "¿Puedo hacer una pregunta?", "Могу я задать вопрос?", None),
    ("querer", "хотеть / любить", "verb", None, "querer", "Quiero un vaso de agua.", "Я хочу стакан воды.", None),
    ("necesitar", "нуждаться / нужно", "verb", None, "necesitar", "Necesito comprar un billete.", "Мне нужно купить билет.", None),
    ("buscar", "искать", "verb", None, "buscar", "Busco la parada de metro.", "Я ищу остановку метро.", None),
    ("encontrar", "находить", "verb", None, "encontrar", "No encuentro mis llaves.", "Я не нахожу свои ключи.", None),
    ("comprar", "покупать", "verb", None, "comprar", "Compro comida en el mercado.", "Я покупаю еду на рынке.", None),
    ("vender", "продавать", "verb", None, "vender", "Venden libros usados aquí.", "Здесь продают подержанные книги.", None),
    ("pagar", "платить", "verb", None, "pagar", "¿Puedo pagar con tarjeta?", "Могу я оплатить картой?", None),
    ("costar", "стоить", "verb", None, "costar", "¿Cuánto cuesta este café?", "Сколько стоит этот кофе?", None),
    ("abrir", "открывать", "verb", None, "abrir", "Abro la ventana porque hace calor.", "Я открываю окно, потому что жарко.", None),
    ("cerrar", "закрывать", "verb", None, "cerrar", "Cierran la tienda a las nueve.", "Магазин закрывают в девять.", None),
    ("empezar", "начинать", "verb", None, "empezar", "La clase empieza a las nueve.", "Урок начинается в девять.", None),
    ("comenzar", "начинать (синоним)", "verb", None, "comenzar", "Comenzamos la reunión ahora.", "Мы начинаем собрание сейчас.", None),
    ("terminar", "заканчивать", "verb", None, "terminar", "Termino el trabajo a las seis.", "Я заканчиваю работу в шесть.", None),
    ("acabar", "завершать", "verb", None, "acabar", "Acabo de comer.", "Я только что поел.", None),
    ("leer", "читать", "verb", None, "leer", "Leo las noticias por la mañana.", "Я читаю новости по утрам.", None),
    ("escuchar", "слушать", "verb", None, "escuchar", "Escucho música mientras estudio.", "Я слушаю музыку, пока учусь.", None),
    ("oír", "слышать", "verb", None, "oír", "¿Oyes ese ruido?", "Ты слышишь этот шум?", None),
    ("mirar", "смотреть", "verb", None, "mirar", "Miro una película en español.", "Я смотрю фильм на испанском.", None),
    ("ver", "видеть / смотреть", "verb", None, "ver", "Veo a mis amigos los sábados.", "Я вижусь с друзьями по субботам.", None),
    ("enseñar", "обучать / показывать", "verb", None, "enseñar", "La profesora enseña gramática.", "Учительница объясняет грамматику.", None),
    ("comprender", "понимать / осознавать", "verb", None, "comprender", "Comprendo la situación.", "Я понимаю ситуацию.", None),
    ("preguntar", "спрашивать", "verb", None, "preguntar", "Pregunto la hora a una persona.", "Я спрашиваю время у человека.", None),
    ("responder", "отвечать", "verb", None, "responder", "Respondo al correo electrónico.", "Я отвечаю на электронное письмо.", None),
    ("contestar", "отвечать (на вопрос/звонок)", "verb", None, "contestar", "Nadie contesta el teléfono.", "Никто не отвечает на звонок.", None),
    ("pedir", "просить / заказывать", "verb", None, "pedir", "Pido la cuenta al camarero.", "Я прошу счет у официанта.", None),
    ("dar", "давать", "verb", None, "dar", "¿Me das tu número de teléfono?", "Дашь мне свой номер телефона?", None),
    ("tomar", "брать / пить / садиться на транспорт", "verb", None, "tomar", "Tomo el autobús número diez.", "Я сажусь на автобус номер десять.", None),
    ("llevar", "носить / нести / подвозить", "verb", None, "llevar", "Llevo una chaqueta azul.", "На мне синяя куртка.", None),
    ("traer", "приносить", "verb", None, "traer", "¿Me traes un vaso de agua?", "Принесёшь мне стакан воды?", None),
    ("poner", "класть / ставить / включать", "verb", None, "poner", "Pongo el libro sobre la mesa.", "Я кладу книгу на стол.", None),
    ("quitar", "убирать / снимать", "verb", None, "quitar", "Me quito los zapatos al entrar.", "Я снимаю обувь при входе.", None),
    ("dejar", "оставлять / позволять", "verb", None, "dejar", "Dejo las llaves en la mesa.", "Я оставляю ключи на столе.", None),
    ("usar", "использовать", "verb", None, "usar", "Uso el diccionario para traducir.", "Я пользуюсь словарем для перевода.", None),
    ("utilizar", "использовать (синоним)", "verb", None, "utilizar", "Utilizo el ordenador para trabajar.", "Я использую компьютер для работы.", None),
    ("ayudar", "помогать", "verb", None, "ayudar", "¿Me puedes ayudar con esta frase?", "Можешь помочь мне с этой фразой?", None),
    ("esperar", "ждать / надеяться", "verb", None, "esperar", "Espero el autobús en la parada.", "Я жду автобус на остановке.", None),
    ("recordar", "помнить / вспоминать", "verb", None, "recordar", "No recuerdo esa palabra.", "Я не помню это слово.", None),
    ("olvidar", "забывать", "verb", None, "olvidar", "Siempre olvido el paraguas.", "Я всегда забываю зонт.", None),
    ("saber", "знать (факты, умения)", "verb", None, "saber", "Sé hablar un poco de español.", "Я умею немного говорить по-испански.", None),
    ("pensar", "думать", "verb", None, "pensar", "Pienso que es una buena idea.", "Я думаю, что это хорошая идея.", None),
    ("creer", "верить / полагать", "verb", None, "creer", "Creo que la tienda está abierta.", "Я полагаю, что магазин открыт.", None),
    ("sentir", "чувствовать", "verb", None, "sentir", "Siento mucho frío aquí.", "Мне очень холодно здесь.", None),
    ("gustar", "нравиться", "verb", None, "gustar", "Me gusta la música latina.", "Мне нравится латиноамериканская музыка.", None),
    ("encantar", "очень нравиться / обожать", "verb", None, "encantar", "Me encanta la comida española.", "Я обожаю испанскую еду.", None),
    ("preferir", "предпочитать", "verb", None, "preferir", "Prefiero té en vez de café.", "Я предпочитаю чай вместо кофе.", None),
    ("limpiar", "убирать / чистить", "verb", None, "limpiar", "Limpio la casa los sábados.", "Я убираю дом по субботам.", None),
    ("cocinar", "готовить еду", "verb", None, "cocinar", "Cocino una paella los domingos.", "Я готовлю паэлью по воскресеньям.", None),
    ("lavar", "мыть / стирать", "verb", None, "lavar", "Lavo los platos después de cenar.", "Я мою посуду после ужина.", None),
    ("jugar", "играть", "verb", None, "jugar", "Juego al fútbol con mis amigos.", "Я играю в футбол с друзьями.", None),
    ("bailar", "танцевать", "verb", None, "bailar", "Bailamos salsa los viernes.", "Мы танцуем сальсу по пятницам.", None),
]

# 7. DESCRIPTIONS (55 lemmas) - unit: a1-u03-identity
descriptions_words = [
    ("grande", "большой", "adjective", "m", "grande", "Madrid tiene plazas muy grandes.", "В Мадриде очень большие площади.", "gran перед сущ."),
    ("pequeño", "маленький", "adjective", "m", "pequeño", "Vivo en un apartamento pequeño.", "Я живу в маленькой квартире.", None),
    ("alto", "высокий", "adjective", "m", "alto", "Ese edificio es muy alto.", "Вон то здание очень высокое.", None),
    ("bajo", "низкий / невысокий", "adjective", "m", "bajo", "Mi hermano es más bajo que yo.", "Мой брат ниже меня.", None),
    ("gordo", "полный / толстый", "adjective", "m", "gordo", "El gato está un poco gordo.", "Кот немного толстый.", None),
    ("delgado", "худой / стройный", "adjective", "m", "delgado", "Es una persona delgada y ágil.", "Это стройный и подвижный человек.", None),
    ("joven", "молодой", "adjective", "m", "joven", "El profesor es muy joven.", "Преподаватель очень молодой.", None),
    ("viejo", "старый", "adjective", "m", "viejo", "Es un coche viejo pero fiable.", "Это старая, но надежная машина.", None),
    ("nuevo", "новый", "adjective", "m", "nuevo", "Tengo un teléfono nuevo.", "У меня новый телефон.", None),
    ("antiguo", "старинный / древний", "adjective", "m", "antiguo", "Visitamos una iglesia antigua.", "Мы посетили старинную церковь.", None),
    ("bueno", "хороший", "adjective", "m", "bueno", "Es un buen amigo.", "Это хороший друг.", "buen перед муж. родом"),
    ("malo", "плохой", "adjective", "m", "malo", "Hoy hace mal tiempo.", "Сегодня плохая погода.", "mal перед муж. родом"),
    ("bonito", "красивый / симпатичный", "adjective", "m", "bonito", "Esta ciudad es muy bonita.", "Этот город очень красивый.", None),
    ("hermoso", "прекрасный / красивый", "adjective", "m", "hermoso", "El paisaje es hermoso.", "Пейзаж прекрасен.", None),
    ("feo", "некрасивый", "adjective", "m", "feo", "El clima hoy está muy feo.", "Погода сегодня очень неприятная.", None),
    ("simpático", "приятный / милый", "adjective", "m", "simpático", "La dependienta es muy simpática.", "Продавщица очень приветливая.", None),
    ("antipático", "неприятный / нелюбезный", "adjective", "m", "antipático", "El camarero fue antipático.", "Официант был нелюбезным.", None),
    ("amable", "любезный / вежливый", "adjective", "m", "amable", "Muchas gracias, muy amable.", "Большое спасибо, очень любезно.", None),
    ("inteligente", "умный", "adjective", "m", "inteligente", "Mi hermana es muy inteligente.", "Моя сестра очень умная.", None),
    ("trabajador", "трудолюбивый", "adjective", "m", "trabajador", "Es un chico muy trabajador.", "Это очень трудолюбивый парень.", None),
    ("tímido", "застенчивый / робкий", "adjective", "m", "tímido", "De niño era muy tímido.", "В детстве я был очень застенчивым.", None),
    ("divertido", "весёлый / забавный", "adjective", "m", "divertido", "La película es muy divertida.", "Фильм очень забавный.", None),
    ("aburrido", "скучный / скучающий", "adjective", "m", "aburrido", "El libro es un poco aburrido.", "Книга немного скучная.", None),
    ("interesante", "интересный", "adjective", "m", "interesante", "Esta conversación es muy interesante.", "Этот разговор очень интересный.", None),
    ("fácil", "лёгкий / простой", "adjective", "m", "fácil", "El examen fue bastante fácil.", "Экзамен был довольно лёгким.", None),
    ("difícil", "трудный / сложный", "adjective", "m", "difícil", "La pronunciación es un poco difícil.", "Произношение немного сложное.", None),
    ("importante", "важный", "adjective", "m", "importante", "Es un documento muy importante.", "Это очень важный документ.", None),
    ("rápido", "быстрый", "adjective", "m", "rápido", "El tren de alta velocidad es rápido.", "Скоростной поезд быстрый.", None),
    ("lento", "медленный", "adjective", "m", "lento", "El autobús de la ciudad es lento.", "Городской автобус медленный.", None),
    ("limpio", "чистый", "adjective", "m", "limpio", "La habitación está muy limpia.", "Комната очень чистая.", None),
    ("sucio", "грязный", "adjective", "m", "sucio", "El suelo está sucio.", "Пол грязный.", None),
    ("caro", "дорогой (по цене)", "adjective", "m", "caro", "Ese restaurante es muy caro.", "Тот ресторан очень дорогой.", None),
    ("barato", "дешёвый", "adjective", "m", "barato", "El menú del día es barato.", "Меню дня дешевое.", None),
    ("feliz", "счастливый", "adjective", "m", "feliz", "Hoy estoy muy feliz.", "Сегодня я очень счастлив.", None),
    ("triste", "грустный", "adjective", "m", "triste", "La música suena triste.", "Музыка звучит грустно.", None),
    ("cansado", "уставший", "adjective", "m", "cansado", "Estoy cansado después del trabajo.", "Я устал после работы.", None),
    ("enfermo", "больной", "adjective", "m", "enfermo", "Hoy no voy a clase porque estoy enfermo.", "Сегодня я не иду на урок, потому что болен.", None),
    ("contento", "довольный / радостный", "adjective", "m", "contento", "Estoy muy contento con el curso.", "Я очень доволен курсом.", None),
    ("ocupado", "занятый", "adjective", "m", "ocupado", "El médico está ocupado ahora.", "Врач сейчас занят.", None),
    ("libre", "свободный", "adjective", "m", "libre", "¿Estás libre esta tarde?", "Ты свободен сегодня вечером?", None),
    ("tranquilo", "спокойный / тихий", "adjective", "m", "tranquilo", "Es un barrio muy tranquilo.", "Это очень тихий район.", None),
    ("nervioso", "нервный / взволнованный", "adjective", "m", "nervioso", "Estoy un poco nervioso por el examen.", "Я немного волнуюсь из-за экзамена.", None),
    ("rojo", "красный", "adjective", "m", "rojo", "Tengo un cuaderno rojo.", "У меня красная тетрадь.", None),
    ("azul", "синий / голубой", "adjective", "m", "azul", "El cielo está completamente azul.", "Небо совершенно синее.", None),
    ("verde", "зелёный", "adjective", "m", "verde", "Las hojas de los árboles son verdes.", "Листья на деревьях зеленые.", None),
    ("amarillo", "жёлтый", "adjective", "m", "amarillo", "La flor amarilla huele muy bien.", "Жёлтый цветок приятно пахнет.", None),
    ("blanco", "белый", "adjective", "m", "blanco", "Lleva una camisa blanca.", "На нём белая рубашка.", None),
    ("negro", "чёрный", "adjective", "m", "negro", "El gato negro duerme en el sofá.", "Чёрный кот спит на диване.", None),
    ("gris", "серый", "adjective", "m", "gris", "Hoy el día está gris y nublado.", "Сегодня день серый и пасмурный.", None),
    ("marrón", "коричневый", "adjective", "m", "marrón", "Tengo zapatos marrones.", "У меня коричневые туфли.", "В Лат. Америке: café"),
    ("rosa", "розовый", "adjective", "m", "rosa", "Compré una camiseta rosa.", "Я купил розовую футболку.", None),
    ("naranja (color)", "оранжевый", "adjective", "m", "naranja (color)", "El autobús es de color naranja.", "Автобус оранжевого цвета.", None),
    ("rubio", "светловолосый / блондин", "adjective", "m", "rubio", "El chico rubio es mi primo.", "Светловолосый парень — мой кузен.", None),
    ("moreno", "темноволосый / смуглый", "adjective", "m", "moreno", "Tiene el pelo moreno y rizado.", "У неё тёмные кудрявые волосы.", None),
    ("caliente", "горячий", "adjective", "m", "caliente", "El té está muy caliente.", "Чай очень горячий.", None),
]

# 8. CLOTHES-SHOPPING (50 lemmas) - unit: a1-u09-needs
clothes_shopping_words = [
    ("ropa", "одежда", "noun", "f", "ropa", "Compro ropa de verano.", "Я покупаю летнюю одежду.", "Всегда ед. число"),
    ("camisa", "рубашка", "noun", "f", "camisa", "Una camisa blanca elegante.", "Элегантная белая рубашка.", None),
    ("camiseta", "футболка", "noun", "f", "camiseta", "Llevo una camiseta de algodón.", "На мне хлопковая футболка.", "В Аргентине: remera"),
    ("pantalones", "брюки / штаны", "noun", "m", "pantalones", "Estos pantalones son cómodos.", "Эти брюки удобные.", None),
    ("vaqueros", "джинсы", "noun", "m", "vaqueros", "Compré unos vaqueros azules.", "Я купил синие джинсы.", "В Лат. Америке: jeans/pantalones de mezclilla"),
    ("vestido", "платье", "noun", "m", "vestido", "El vestido rojo es precioso.", "Красное платье великолепно.", None),
    ("falda", "юбка", "noun", "f", "falda", "Lleva una falda corta.", "На ней короткая юбка.", "В Лат. Америке: pollera"),
    ("chaqueta", "куртка / жакет / пиджак", "noun", "f", "chaqueta", "Ponte la chaqueta porque hace frío.", "Надень куртку, потому что холодно.", None),
    ("abrigo", "пальто / тёплая куртка", "noun", "m", "abrigo", "En invierno llevo un abrigo grueso.", "Зимой я ношу толстое пальто.", None),
    ("jersey", "свитер / джемпер", "noun", "m", "jersey", "Este jersey de lana es muy suave.", "Этот шерстяной свитер очень мягкий.", "В Лат. Америке: suéter/chomba"),
    ("suéter", "свитер", "noun", "m", "suéter", "Me pongo un suéter abrigado.", "Я надеваю тёплый свитер.", None),
    ("zapatos", "туфли / обувь", "noun", "m", "zapatos", "Mis zapatos son de cuero.", "Мои туфли из кожи.", None),
    ("zapatillas", "кроссовки / тапочки", "noun", "f", "zapatillas", "Corro con zapatillas deportivas.", "Я бегаю в кроссовках.", "В Лат. Америке: tenis/championes"),
    ("botas", "сапоги / ботинки", "noun", "f", "botas", "Llevo botas cuando llueve.", "Я ношу сапоги, когда идёт дождь.", None),
    ("calcetines", "носки", "noun", "m", "calcetines", "Tengo calcetines de lana.", "У меня есть шерстяные носки.", "В Лат. Америке: medias"),
    ("sombrero", "шляпа", "noun", "m", "sombrero", "Lleva un sombrero para el sol.", "Он носит шляпу от солнца.", None),
    ("gorra", "кепка / бейсболка", "noun", "f", "gorra", "Me pongo la gorra en verano.", "Я надеваю кепку летом.", None),
    ("bufanda", "шарф", "noun", "f", "bufanda", "La bufanda me protege del viento.", "Шарф защищает меня от ветра.", None),
    ("guantes", "перчатки", "noun", "m", "guantes", "Mis manos tienen frío sin guantes.", "Мои руки мёрзнут без перчаток.", None),
    ("cinturón", "ремень / пояс", "noun", "m", "cinturón", "Este cinturón me queda grande.", "Этот ремень мне велик.", None),
    ("bolso", "сумка (дамская)", "noun", "m", "bolso", "Guardo la cartera en el bolso.", "Я храню кошелек в сумке.", None),
    ("mochila", "рюкзак", "noun", "f", "mochila", "Llevo los libros en la mochila.", "Я несу книги в рюкзаке.", None),
    ("cartera", "кошелёк / портмоне", "noun", "f", "cartera", "No tengo efectivo en la cartera.", "У меня нет наличных в кошельке.", "В Лат. Америке: billetera"),
    ("gafas", "очки", "noun", "f", "gafas", "Llevo gafas de sol en la playa.", "Я ношу солнечные очки на пляже.", "В Лат. Америке: lentes/anteojos"),
    ("reloj", "часы (наручные)", "noun", "m", "reloj", "Miro la hora en mi reloj.", "Я смотрю время на своих часах.", None),
    ("paraguas", "зонт", "noun", "m", "paraguas", "Lleva el paraguas porque va a llover.", "Возьми зонт, потому что будет дождь.", "Мужской род: el paraguas"),
    ("traje", "костюм", "noun", "m", "traje", "Lleva traje y corbata al trabajo.", "Он носит костюм и галстук на работу.", None),
    ("corbata", "галстук", "noun", "f", "corbata", "La corbata es de seda.", "Галстук из шёлка.", None),
    ("bañador", "купальник / плавки", "noun", "m", "bañador", "Llevo el bañador a la piscina.", "Я беру плавки в бассейн.", "В Лат. Америке: traje de baño/malla"),
    ("pijama", "пижама", "noun", "m", "pijama", "Me pongo el pijama para dormir.", "Я надеваю пижаму ко сну.", None),
    ("centro comercial", "торговый центр", "noun", "m", "centro comercial", "Vamos de compras al centro comercial.", "Мы идём за покупками в торговый центр.", None),
    ("precio", "цена", "noun", "m", "precio", "¿Cuál es el precio de esta camisa?", "Какова цена этой рубашки?", None),
    ("dinero", "деньги", "noun", "m", "dinero", "No tengo suficiente dinero.", "У меня недостаточно денег.", None),
    ("euro", "евро", "noun", "m", "euro", "Cuesta quince euros.", "Это стоит пятнадцать евро.", None),
    ("dólar", "доллар", "noun", "m", "dólar", "El precio es en dólares.", "Цена в долларах.", None),
    ("peso", "песо", "noun", "m", "peso", "En Argentina se paga en pesos.", "В Аргентине платят в песо.", None),
    ("tarjeta de crédito", "кредитная карта", "noun", "f", "tarjeta de crédito", "¿Aceptan tarjeta de crédito?", "Вы принимаете кредитные карты?", None),
    ("efectivo", "наличные деньги", "noun", "m", "efectivo", "Pago en efectivo.", "Я плачу наличными.", None),
    ("rebajas", "скидки / распродажа", "noun", "f", "rebajas", "Hay grandes rebajas en enero.", "В январе большие скидки.", "Обычно во мн. числе"),
    ("descuento", "скидка", "noun", "m", "descuento", "Tiene un veinte por ciento de descuento.", "Здесь скидка двадцать процентов.", None),
    ("talla", "размер (одежды)", "noun", "f", "talla", "¿Qué talla tiene esta chaqueta?", "Какой размер у этой куртки?", None),
    ("número (calzado)", "размер (обуви)", "noun", "m", "número (calzado)", "Calzo el número cuarenta y dos.", "Я ношу 42-й размер обуви.", None),
    ("probador", "примерочная кабина", "noun", "m", "probador", "¿Dónde están los probadores?", "Где находятся примерочные?", None),
    ("caja", "касса (в магазине)", "noun", "f", "caja", "Pague en la caja número dos.", "Оплатите в кассе номер два.", None),
    ("recibo", "чек / квитанция", "noun", "m", "recibo", "Guarde su recibo de compra.", "Сохраните ваш чек о покупке.", "В Лат. Америке: ticket/factura"),
    ("bolsa", "пакет / сумка для покупок", "noun", "f", "bolsa", "¿Desea una bolsa para la compra?", "Желаете пакет для покупок?", None),
    ("probarse", "примерять на себя", "verb", None, "probarse", "¿Puedo probarme este vestido?", "Могу я примерить это платье?", None),
    ("quedar bien", "хорошо сидеть (об одежде)", "phrase", None, "quedar bien", "Esta camisa te queda muy bien.", "Эта рубашка тебе очень идёт.", None),
    ("devolver", "возвращать (товар)", "verb", None, "devolver", "Quiero devolver este pantalón.", "Я хочу вернуть эти брюки.", None),
    ("cambiar (ropa)", "менять / обменивать", "verb", None, "cambiar (ropa)", "¿Puedo cambiarlo por otra talla?", "Могу я обменять это на другой размер?", None),
]

# 9. TRANSPORT-DIRECTIONS (45 lemmas) - unit: a1-u08-home
transport_directions_words = [
    ("coche", "машина / автомобиль", "noun", "m", "coche", "Voy al trabajo en coche.", "Я еду на работу на машине.", "В Лат. Америке: carro/auto"),
    ("auto", "автомобиль", "noun", "m", "auto", "El auto está aparcado enfrente.", "Автомобиль припаркован напротив.", "Распространено в Аргентине и Лат. Америке"),
    ("taxi", "такси", "noun", "m", "taxi", "Tomo un taxi para ir al aeropuerto.", "Я беру такси, чтобы поехать в аэропорт.", None),
    ("autobús", "автобус", "noun", "m", "autobús", "El autobús llega en cinco minutos.", "Автобус приедет через пять минут.", "В Аргентине: colectivo, на Кубе: guagua"),
    ("metro", "метро", "noun", "m", "metro", "La estación de metro está cerca.", "Станция метро находится рядом.", "В Буэнос-Айресе: subte"),
    ("tren", "поезд", "noun", "m", "tren", "El tren a Sevilla sale a las tres.", "Поезд в Севилью отправляется в три.", None),
    ("avión", "самолёт", "noun", "m", "avión", "El avión aterriza a tiempo.", "Самолёт приземляется вовремя.", None),
    ("bicicleta", "велосипед", "noun", "f", "bicicleta", "Voy en bicicleta por el parque.", "Я еду на велосипеде по парку.", "Сокр.: bici"),
    ("moto", "мотоцикл", "noun", "f", "moto", "Viaja por la ciudad en moto.", "Он передвигается по городу на мотоцикле.", "Женский род: la moto"),
    ("barco", "корабль / лодка", "noun", "m", "barco", "El barco cruza el río.", "Корабль переплывает реку.", None),
    ("billete", "билет", "noun", "m", "billete", "Un billete de ida y vuelta, por favor.", "Один билет туда и обратно, пожалуйста.", "В Лат. Америке: boleto/pasaje"),
    ("boleto", "билет (Лат. Америка)", "noun", "m", "boleto", "Compré mi boleto en línea.", "Я купил свой билет онлайн.", None),
    ("parada", "остановка", "noun", "f", "parada", "¿Dónde está la parada de autobús?", "Где остановка автобуса?", None),
    ("aeropuerto", "аэропорт", "noun", "m", "aeropuerto", "Llegamos al aeropuerto temprano.", "Мы прибыли в аэропорт рано.", None),
    ("puerto", "порт", "noun", "m", "puerto", "Hay muchos barcos en el puerto.", "В порту много кораблей.", None),
    ("andén", "платформа / перрон", "noun", "m", "andén", "El tren sale del andén cuatro.", "Поезд отправляется с четвертой платформы.", None),
    ("vuelo", "рейс / полёт", "noun", "m", "vuelo", "Mi vuelo sale a las siete.", "Мой рейс вылетает в семь.", None),
    ("esquina", "угол (улицы)", "noun", "f", "esquina", "Gira a la derecha en la esquina.", "Поверни направо на углу.", None),
    ("mapa", "карта", "noun", "m", "mapa", "Miro el mapa en el móvil.", "Я смотрю карту на телефоне.", "Мужской род: el mapa"),
    ("norte", "север", "noun", "m", "norte", "El norte del país es verde.", "Север страны зелёный.", None),
    ("sur", "юг", "noun", "m", "sur", "En el sur hace mucho sol.", "На юге очень солнечно.", None),
    ("este", "восток", "noun", "m", "este", "El sol sale por el este.", "Солнце встает на востоке.", None),
    ("oeste", "запад", "noun", "m", "oeste", "Caminamos hacia el oeste.", "Мы идём на запад.", None),
    ("derecha", "право / правая сторона", "noun", "f", "derecha", "La farmacia está a la derecha.", "Аптека находится справа.", None),
    ("izquierda", "лево / левая сторона", "noun", "f", "izquierda", "Gira a la izquierda en el semáforo.", "Поверни налево на светофоре.", None),
    ("recto", "прямо", "adverb", None, "recto", "Siga todo recto dos calles.", "Идите прямо две улицы.", None),
    ("todo seguido", "всё время прямо", "phrase", None, "todo seguido", "Continúe todo seguido hasta la plaza.", "Продолжайте прямо до площади.", None),
    ("cerca", "близко / рядом", "adverb", None, "cerca", "El hotel está muy cerca de la estación.", "Отель очень близко от вокзала.", None),
    ("lejos", "далеко", "adverb", None, "lejos", "El aeropuerto está lejos del centro.", "Аэропорт далеко от центра.", None),
    ("aquí", "здесь / тут", "adverb", None, "aquí", "Mi casa está здесь.", "Мой дом здесь.", "В Лат. Америке также: acá"),
    ("allí", "там", "adverb", None, "allí", "El museo está allí, al fondo.", "Музей там, в глубине.", "В Лат. Америке также: allá"),
    ("enfrente", "напротив", "adverb", None, "enfrente", "El banco está enfrente del parque.", "Банк находится напротив парка.", None),
    ("al lado de", "рядом с / около", "preposition", None, "al lado de", "La tienda está al lado del café.", "Магазин находится рядом с кафе.", None),
    ("entre", "между", "preposition", None, "entre", "El cine está entre el banco y la farmacia.", "Кинотеатр между банком и аптекой.", None),
    ("semáforo", "светофор", "noun", "m", "semáforo", "Cruza cuando el semáforo esté verde.", "Переходи, когда светофор зелёный.", None),
    ("paso de peatones", "пешеходный переход", "noun", "m", "paso de peatones", "Cruzo por el paso de peatones.", "Я перехожу по пешеходному переходу.", None),
    ("tráfico", "дорожное движение / трафик", "noun", "m", "tráfico", "Hay mucho tráfico a esta hora.", "В этот час сильное движение.", None),
    ("parar", "останавливать / останавливаться", "verb", None, "parar", "El taxi para en la puerta.", "Такси останавливается у двери.", None),
    ("cruzar", "переходить / пересекать", "verb", None, "cruzar", "Cruzo la calle con cuidado.", "Я осторожно перехожу улицу.", None),
    ("girar", "поворачивать", "verb", None, "girar", "Gira en la primera calle a la derecha.", "Поверни на первой улице направо.", None),
    ("doblar", "поворачивать (Лат. Америка)", "verb", None, "doblar", "Doble a la izquierda en la esquina.", "Поверните налево на углу.", None),
    ("seguir", "следовать / продолжать путь", "verb", None, "seguir", "Siga recto hasta el final.", "Следуйте прямо до конца.", None),
    ("subir", "подниматься / садиться (в транспорт)", "verb", None, "subir", "Subo al autobús en la esquina.", "Я сажусь в автобус на углу.", None),
    ("bajar", "спускаться / выходить (из транспорта)", "verb", None, "bajar", "Bajo en la próxima estación.", "Я выхожу на следующей станции.", None),
    ("perderse", "теряться / заблудиться", "verb", None, "perderse", "Me perdí en el centro histórico.", "Я заблудился в историческом центре.", None),
]

# 10. WEATHER-LEISURE (45 lemmas) - unit: a1-u09-needs
weather_leisure_words = [
    ("tiempo (clima)", "погода", "noun", "m", "tiempo (clima)", "¿Qué tiempo hace hoy?", "Какая сегодня погода?", None),
    ("clima", "климат", "noun", "m", "clima", "El clima en el sur es templado.", "Климат на юге мягкий.", None),
    ("sol", "солнце", "noun", "m", "sol", "Hoy hace mucho sol.", "Сегодня очень солнечно.", None),
    ("lluvia", "дождь", "noun", "f", "lluvia", "La lluvia limpia el aire.", "Дождь очищает воздух.", None),
    ("viento", "ветер", "noun", "m", "viento", "Hace mucho viento en la costa.", "На побережье сильный ветер.", None),
    ("nieve", "снег", "noun", "f", "nieve", "Hay mucha nieve en la montaña.", "В горах много снега.", None),
    ("calor", "жара / тепло", "noun", "m", "calor", "En agosto hace mucho calor.", "В августе очень жарко.", None),
    ("frío", "холод", "noun", "m", "frío", "En invierno hace frío.", "Зимой холодно.", None),
    ("nube", "облако / туча", "noun", "f", "nube", "El cielo está cubierto de nubes.", "Небо покрыто облаками.", None),
    ("tormenta", "гроза / буря", "noun", "f", "tormenta", "Viene una tormenta fuerte.", "Приближается сильная гроза.", None),
    ("cielo", "небо", "noun", "m", "cielo", "El cielo está despejado hoy.", "Небо сегодня ясное.", None),
    ("llover", "идти (о дожде)", "verb", None, "llover", "Está lloviendo mucho ahora.", "Сейчас идёт сильный дождь.", None),
    ("nevar", "идти (о снеге)", "verb", None, "nevar", "Nieva en las montañas en enero.", "В горах идёт снег в январе.", None),
    ("primavera", "весна", "noun", "f", "primavera", "La primavera empieza en marzo.", "Весна начинается в марте.", None),
    ("verano", "лето", "noun", "m", "verano", "En verano voy a la playa.", "Летом я езжу на пляж.", None),
    ("otoño", "осень", "noun", "m", "otoño", "En otoño caen las hojas.", "Осенью опадают листья.", None),
    ("invierno", "зима", "noun", "m", "invierno", "En invierno llevo abrigo y guantes.", "Зимой я ношу пальто и перчатки.", None),
    ("música", "музыка", "noun", "f", "música", "Me gusta escuchar música clásica.", "Мне нравится слушать классическую музыку.", None),
    ("canción", "песня", "noun", "f", "canción", "Esta canción es muy pegadiza.", "Эта песня очень запоминающаяся.", None),
    ("concierto", "концерт", "noun", "m", "concierto", "Vamos a un concierto de rock.", "Мы идём на рок-концерт.", None),
    ("fiesta", "праздник / вечеринка", "noun", "f", "fiesta", "El sábado celebramos una fiesta.", "В субботу мы празднуем вечеринку.", None),
    ("película", "фильм", "noun", "f", "película", "Vemos una película divertida.", "Мы смотрим весёлый фильм.", None),
    ("libro", "книга", "noun", "m", "libro", "Leo un libro en español.", "Я читаю книгу на испанском.", None),
    ("deporte", "спорт", "noun", "m", "deporte", "Hago deporte tres veces por semana.", "Я занимаюсь спортом три раза в неделю.", None),
    ("fútbol", "футбол", "noun", "m", "fútbol", "El fútbol es muy popular en España.", "Футбол очень популярен в Испании.", None),
    ("baloncesto", "баскетбол", "noun", "m", "baloncesto", "Juego al baloncesto los jueves.", "Я играю в баскетбол по четвергам.", "В Лат. Америке: básquetbol"),
    ("tenis", "теннис", "noun", "m", "tenis", "Juego al tenis con mi hermano.", "Я играю в теннис с братом.", None),
    ("natación", "плавание", "noun", "f", "natación", "La natación es buena para la espalda.", "Плавание полезно для спины.", None),
    ("piscina", "бассейн", "noun", "f", "piscina", "Nado en la piscina municipal.", "Я плаваю в городском бассейне.", "В Лат. Америке: alberca/pileta"),
    ("montaña", "гора", "noun", "f", "montaña", "Caminamos por la montaña el domingo.", "Мы гуляем по горам в воскресенье.", None),
    ("mar", "море", "noun", "m", "mar", "Nado en el mar Mediterráneo.", "Я плаваю в Средиземном море.", "el mar / la mar"),
    ("bosque", "лес", "noun", "m", "bosque", "Paseamos por el bosque en otoño.", "Мы гуляем по лесу осенью.", None),
    ("río", "река", "noun", "m", "río", "El río cruza la ciudad.", "Река протекает через город.", None),
    ("vacaciones", "каникулы / отпуск", "noun", "f", "vacaciones", "Tengo vacaciones en agosto.", "У меня отпуск в августе.", "Обычно во мн. числе"),
    ("viaje", "поездка / путешествие", "noun", "m", "viaje", "¡Buen viaje a España!", "Счастливого пути в Испанию!", None),
    ("foto", "фотография", "noun", "f", "foto", "Hago muchas fotos de las vacaciones.", "Я делаю много фотографий из отпуска.", "Женский род: la foto"),
    ("cámara", "фотоаппарат / камера", "noun", "f", "cámara", "Llevo la cámara de fotos.", "Я несу фотоаппарат.", None),
    ("nadar", "плавать", "verb", None, "nadar", "Nado en la playa en verano.", "Я плаваю на пляже летом.", None),
    ("cantar", "петь", "verb", None, "cantar", "Canto canciones en la ducha.", "Я пою песни в душе.", None),
    ("pasear", "прогуливаться", "verb", None, "pasear", "Paseo con mi perro cada tarde.", "Я гуляю с собакой каждый вечер.", None),
    ("pintar", "рисовать / красить", "verb", None, "pintar", "Pinto cuadros de paisajes.", "Я рисую пейзажи.", None),
    ("dibujar", "рисовать карандашом", "verb", None, "dibujar", "Mi hijo dibuja animales.", "Мой сын рисует животных.", None),
    ("tocar (instrumento)", "играть (на инструменте)", "verb", None, "tocar (instrumento)", "Toco la guitarra en mis ratos libres.", "Я играю на гитаре в свободное время.", None),
    ("guitarra", "гитара", "noun", "f", "guitarra", "La guitarra española suena hermosa.", "Испанская гитара звучит прекрасно.", None),
    ("piano", "пианино / фортепиано", "noun", "m", "piano", "Estudia piano en el conservatorio.", "Она учится играть на пианино.", None),
]

# 11. FUNCTION-WORDS (45 lemmas) - unit: a1-u05-actions
function_words = [
    ("y", "и", "conjunction", None, "y", "Estudio español y trabajo.", "Я учу испанский и работаю.", "e перед словами на i-/hi-"),
    ("e", "и (перед звуком [и])", "conjunction", None, "e", "Hablo español e inglés.", "Я говорю по-испански и по-английски.", None),
    ("o", "или", "conjunction", None, "o", "¿Prefieres té o café?", "Ты предпочитаешь чай или кофе?", "u перед словами на o-/ho-"),
    ("u", "или (перед звуком [о])", "conjunction", None, "u", "Siete u ocho personas.", "Семь или восемь человек.", None),
    ("pero", "но", "conjunction", None, "pero", "Estudio mucho, pero es difícil.", "Я много занимаюсь, но это сложно.", None),
    ("porque", "потому что", "conjunction", None, "porque", "Estudio español porque me gusta.", "Я учу испанский, потому что мне нравится.", None),
    ("por eso", "поэтому / из-за этого", "phrase", None, "por eso", "Tengo examen mañana, por eso estudio.", "Завтра экзамен, поэтому я учусь.", None),
    ("entonces", "тогда / в таком случае", "conjunction", None, "entonces", "Si estás cansado, entonces descansa.", "Если ты устал, тогда отдохни.", None),
    ("mientras", "пока / в то время как", "conjunction", None, "mientras", "Escucho música mientras trabajo.", "Я слушаю музыку, пока работаю.", None),
    ("con", "с (предлог)", "preposition", None, "con", "Voy al cine con mi amigo.", "Я иду в кино со своим другом.", None),
    ("sin", "без (предлог)", "preposition", None, "sin", "Tomo café sin azúcar.", "Я пью кофе без сахара.", None),
    ("de", "из / от / принадлежность", "preposition", None, "de", "Soy de Madrid. El libro de Juan.", "Я из Мадрида. Книга Хуана.", None),
    ("en", "в / на (местоположение)", "preposition", None, "en", "Vivo en una ciudad grande.", "Я живу в большом городе.", None),
    ("a", "в / к (направление, вин. падеж лица)", "preposition", None, "a", "Voy a la escuela. Veo a María.", "Я иду в школу. Я вижу Марию.", None),
    ("por", "по / из-за / в течение", "preposition", None, "por", "Camino por la calle.", "Я гуляю по улице.", None),
    ("para", "для / чтобы / по направлению к", "preposition", None, "para", "Este regalo es para ti.", "Этот подарок для тебя.", None),
    ("sobre", "на / о / над", "preposition", None, "sobre", "El libro está sobre la mesa.", "Книга лежит на столе.", None),
    ("durante", "в течение / во время", "preposition", None, "bajo", "Estudio durante el día.", "Я занимаюсь в течение дня.", None),
    ("debajo de", "под чем-то", "preposition", None, "debajo de", "El gato está debajo de la cama.", "Кот сидит под кроватью.", None),
    ("encima de", "сверху над чем-то", "preposition", None, "encima de", "Las llaves están encima del mueble.", "Ключи на тумбочке.", None),
    ("delante de", "впереди / перед", "preposition", None, "delante de", "La parada está delante del hotel.", "Остановка перед отелем.", None),
    ("detrás de", "позади / за", "preposition", None, "detrás de", "El jardín está detrás de la casa.", "Сад позади дома.", None),
    ("hasta", "до (предлог времени/места)", "preposition", None, "hasta", "Trabajo hasta las seis.", "Я работаю до шести.", None),
    ("desde", "от / с (начальная точка)", "preposition", None, "desde", "Camino desde el centro hasta casa.", "Я иду пешком от центра до дома.", None),
    ("hacia", "по направлению к", "preposition", None, "hacia", "Caminamos hacia la playa.", "Мы идём по направлению к пляжу.", None),
    ("muy", "очень", "adverb", None, "muy", "Estoy muy contento hoy.", "Я сегодня очень доволен.", "Перед прил. и нареч."),
    ("mucho", "много", "adverb", None, "mucho", "Trabajo mucho esta semana.", "Я много работаю на этой неделе.", "После глаголов или перед сущ."),
    ("poco", "мало / немного", "adverb", None, "poco", "Hablo un poco de español.", "Я говорю немного по-испански.", None),
    ("bastante", "достаточно / довольно", "adverb", None, "bastante", "El examen fue bastante largo.", "Экзамен был довольно длинным.", None),
    ("más", "больше / более", "adverb", None, "más", "Quiero un poco más de agua.", "Я хочу еще немного воды.", None),
    ("menos", "меньше / менее", "adverb", None, "menos", "Cuesta menos de diez euros.", "Это стоит меньше десяти евро.", None),
    ("también", "также / тоже", "adverb", None, "también", "Yo también estudio español.", "Я тоже учу испанский.", None),
    ("tampoco", "также не / тоже не", "adverb", None, "tampoco", "Yo tampoco hablo alemán.", "Я тоже не говорю по-немецки.", None),
    ("siempre", "всегда", "adverb", None, "siempre", "Siempre desayuno fruta.", "Я всегда завтракаю фруктами.", None),
    ("nunca", "никогда", "adverb", None, "nunca", "Nunca llego tarde a clase.", "Я никогда не опаздываю на урок.", None),
    ("a veces", "иногда", "phrase", None, "a veces", "A veces cocino pasta.", "Иногда я готовлю пасту.", None),
    ("ya", "уже", "adverb", None, "ya", "Ya son las ocho de la tarde.", "Уже восемь часов вечера.", None),
    ("todavía", "всё ещё / пока ещё", "adverb", None, "todavía", "Todavía no hablo con fluidez.", "Я всё ещё не говорю бегло.", None),
    ("qué", "что / какой", "pronoun", None, "qué", "¿Qué estudias hoy?", "Что ты учишь сегодня?", None),
    ("quién", "кто", "pronoun", None, "quién", "¿Quién es esa persona?", "Кто этот человек?", None),
    ("dónde", "где / куда", "pronoun", None, "dónde", "¿Dónde está la estación?", "Где находится вокзал?", None),
    ("cuándo", "когда", "pronoun", None, "cuándo", "¿Cuándo empieza la clase?", "Когда начинается урок?", None),
    ("cómo", "как", "pronoun", None, "cómo", "¿Cómo se dice esto en español?", "Как это сказать по-испански?", None),
    ("cuánto", "сколько", "pronoun", "m", "cuánto", "¿Cuánto cuesta este billete?", "Сколько стоит этот билет?", None),
    ("por qué", "почему", "phrase", None, "por qué", "¿Por qué estudias español?", "Почему ты учишь испанский?", "Два слова с ударением"),
]

# 12. SURVIVAL-PHRASES (35 lemmas) - unit: a1-u01-first-contact
survival_phrases = [
    ("hola", "привет / здравствуйте", "phrase", None, "hola", "¡Hola! ¿Cómo estás?", "Привет! Как поживаешь?", None),
    ("adiós", "до свидания / прощай", "phrase", None, "adiós", "¡Adiós, nos vemos mañana!", "До свидания, увидимся завтра!", None),
    ("buenos días", "доброе утро", "phrase", None, "buenos días", "¡Buenos días a todos!", "Доброе утро всем!", None),
    ("buenas tardes", "добрый день", "phrase", None, "buenas tardes", "¡Buenas tardes! ¿En qué puedo ayudarle?", "Добрый день! Чем могу вам помочь?", None),
    ("buenas noches", "добрый вечер / спокойной ночи", "phrase", None, "buenas noches", "¡Buenas noches y hasta mañana!", "Доброй ночи и до завтра!", None),
    ("hasta luego", "до скорого / пока", "phrase", None, "hasta luego", "¡Hasta luego, que tengas buen día!", "До скорого, хорошего дня!", None),
    ("hasta pronto", "до скорой встречи", "phrase", None, "hasta pronto", "¡Hasta pronto, amigo!", "До скорой встречи, друг!", None),
    ("hasta mañana", "до завтра", "phrase", None, "hasta mañana", "¡Hasta mañana en clase!", "До завтра на уроке!", None),
    ("por favor", "пожалуйста (просьба)", "phrase", None, "por favor", "Un café con leche, por favor.", "Один кофе с молоком, пожалуйста.", None),
    ("gracias", "спасибо", "phrase", None, "gracias", "Muchas gracias por tu ayuda.", "Большое спасибо за помощь.", None),
    ("de nada", "не за что / пожалуйста", "phrase", None, "de nada", "—Gracias. —De nada, un placer.", "—Спасибо. —Не за что, приятно помочь.", None),
    ("perdón", "простите / извините", "phrase", None, "perdón", "Perdón, ¿dónde está el baño?", "Извините, где находится туалет?", None),
    ("disculpe", "извините (вежливо)", "phrase", None, "disculpe", "Disculpe, ¿este tren va a Madrid?", "Извините, этот поезд идет в Мадрид?", None),
    ("lo siento", "мне жаль / прошу прощения", "phrase", None, "lo siento", "Lo siento, no puedo ir hoy.", "Прошу прощения, я не могу пойти сегодня.", None),
    ("con permiso", "с вашего позволения / разрешите пройти", "phrase", None, "con permiso", "Con permiso, tengo que pasar.", "Разрешите пройти, пожалуйста.", None),
    ("mucho gusto", "очень приятно", "phrase", None, "mucho gusto", "—Me llamo Elena. —Mucho gusto.", "—Меня зовут Елена. —Очень приятно.", None),
    ("encantado", "очень приятно (муж.)", "phrase", None, "encantado", "Encantado de conocerte.", "Очень приятно познакомиться с тобой.", "encantada для женщин"),
    ("¿cómo estás?", "как дела? / как ты?", "phrase", None, "¿cómo estás?", "Hola Juan, ¿cómo estás?", "Привет, Хуан, как поживаешь?", None),
    ("¿qué tal?", "как дела? / как поживаешь?", "phrase", None, "¿qué tal?", "¡Hola! ¿Qué tal todo?", "Привет! Как оно всё?", None),
    ("bien", "хорошо", "adverb", None, "bien", "Muy bien, gracias. ¿Y tú?", "Очень хорошо, спасибо. А ты?", None),
    ("muy bien", "очень хорошо", "phrase", None, "muy bien", "Estoy muy bien, gracias.", "У меня всё отлично, спасибо.", None),
    ("más o menos", "более-менее / так себе", "phrase", None, "más o menos", "Estoy más o menos hoy.", "Я сегодня так себе.", None),
    ("mal", "плохо", "adverb", None, "mal", "Hoy me siento un poco mal.", "Сегодня я чувствую себя неважно.", None),
    ("¿cómo te llamas?", "как тебя зовут?", "phrase", None, "¿cómo te llamas?", "Hola, ¿cómo te llamas tú?", "Привет, а как тебя зовут?", None),
    ("me llamo", "меня зовут...", "phrase", None, "me llamo", "Me llamo Sofía y soy de Lima.", "Меня зовут София, я из Лимы.", None),
    ("¿de dónde eres?", "откуда ты?", "phrase", None, "¿de dónde eres?", "¿De dónde eres tú?", "Откуда ты родом?", None),
    ("soy de", "я из...", "phrase", None, "soy de", "Soy de Argentina.", "Я из Аргентины.", None),
    ("¿cuánto cuesta?", "сколько это стоит?", "phrase", None, "¿cuánto cuesta?", "Disculpe, ¿cuánto cuesta esto?", "Извините, сколько это стоит?", None),
    ("la cuenta por favor", "счёт, пожалуйста", "phrase", None, "la cuenta por favor", "Camarero, la cuenta por favor.", "Официант, счёт, пожалуйста.", None),
    ("no entiendo", "я не понимаю", "phrase", None, "no entiendo", "Perdón, no entiendo la palabra.", "Простите, я не понимаю это слово.", None),
    ("¿puede repetir?", "можете повторить?", "phrase", None, "¿puede repetir?", "¿Puede repetir más despacio, por favor?", "Можете повторить помедленнее, пожалуйста?", None),
    ("más despacio por favor", "помедленнее, пожалуйста", "phrase", None, "más despacio por favor", "Hable más despacio, por favor.", "Говорите помедленнее, пожалуйста.", None),
    ("no hablo español", "я не говорю по-испански", "phrase", None, "no hablo español", "Lo siento, hablo poco español.", "Извините, я мало говорю по-испански.", None),
    ("sí", "да", "adverb", None, "sí", "Sí, claro que sí.", "Да, конечно да.", "С графическим ударением"),
    ("no", "нет", "adverb", None, "no", "No, gracias.", "Нет, спасибо.", None),
]

all_raw_domains = {
    'identity': identity_words,
    'numbers-time': numbers_time_words,
    'people-family': people_family_words,
    'home-city': home_city_words,
    'food': food_words,
    'daily-actions': daily_actions_words,
    'descriptions': descriptions_words,
    'clothes-shopping': clothes_shopping_words,
    'transport-directions': transport_directions_words,
    'weather-leisure': weather_leisure_words,
    'function-words': function_words,
    'survival-phrases': survival_phrases,
}

total_lemmas = 0
all_records = []
seen_keys = set()

for domain, (target_count, unit_id) in DOMAINS_SPEC.items():
    raw_list = all_raw_domains.get(domain, [])
    print(f"Domain '{domain}': raw {len(raw_list)}, target {target_count}")
    if len(raw_list) != target_count:
        raise ValueError(f"Domain mismatch for {domain}: got {len(raw_list)}, expected {target_count}")

    for item in raw_list:
        word, translation, pos, gender, base_form, example, example_tr, notes = item
        key = normalize_key(word)
        if key in seen_keys:
            raise ValueError(f"Duplicate lemma key detected: '{word}' -> key '{key}'")
        seen_keys.add(key)

        record = {
            'word': word,
            'translation': translation,
            'part_of_speech': pos,
            'gender': gender,
            'base_form': base_form or word,
            'course_domain': domain,
            'course_unit_id': unit_id,
            'example': example,
            'example_translation': example_tr,
            'notes': notes,
            'cefr_level': 'A1',
            'is_core_a1': 1
        }
        all_records.append(record)
        total_lemmas += 1

print(f"\nSuccessfully validated {total_lemmas} core A1 lemmas across {len(DOMAINS_SPEC)} domains!")

# Save JSON
with open('/srv/LinguaLearn/spanish/server/a1VocabularyData.json', 'w', encoding='utf-8') as f:
    json.dump(all_records, f, ensure_ascii=False, indent=2)

# Save JS module
with open('/srv/LinguaLearn/spanish/server/a1VocabularyData.js', 'w', encoding='utf-8') as f:
    f.write("/**\n * Complete CEFR A1 Core Vocabulary Dataset\n * Exactly 650 curated lemmas across 12 communicative domains.\n */\n\n")
    f.write("export const A1_CORE_VOCABULARY = Object.freeze(\n")
    f.write(json.dumps(all_records, ensure_ascii=False, indent=2))
    f.write("\n);\n\n")
    f.write("""export function getA1VocabularyByDomain(domainId) {
  return A1_CORE_VOCABULARY.filter(w => w.course_domain === domainId);
}

export function getA1VocabularyByUnit(unitId) {
  return A1_CORE_VOCABULARY.filter(w => w.course_unit_id === unitId);
}
""")

print("Saved server/a1VocabularyData.json and server/a1VocabularyData.js successfully!")
