# A1 raw 300 words
a1_raw = [
  ("hola", "привет", "¡Hola! ¿Cómo estás?"),
  ("buenos días", "доброе утро", "Buenos días, profesor."),
  ("buenas tardes", "добрый день", "Buenas tardes a todos."),
  ("buenas noches", "добрый вечер / спокойной ночи", "Buenas noches, que descanses."),
  ("adiós", "до свидания", "Adiós, hasta mañana."),
  ("hasta luego", "до скорого", "Hasta luego, amigo."),
  ("por favor", "пожалуйста", "Un vaso de agua, por favor."),
  ("gracias", "спасибо", "Muchas gracias por tu ayuda."),
  ("de nada", "не за что", "De nada, fue un placer."),
  ("perdón", "простите / извините", "Perdón, no te escuché bien."),
  ("disculpe", "извините (вежливо)", "Disculpe, ¿dónde está el baño?"),
  ("sí", "да", "Sí, hablo un poco de español."),
  ("no", "нет", "No, no comprendo la pregunta."),
  ("bien", "хорошо", "Todo está muy bien."),
  ("mal", "плохо", "Hoy me siento un poco mal."),
  ("cómo", "как", "¿Cómo te llamas?"),
  ("qué", "что / какой", "¿Qué hora es?"),
  ("quién", "кто", "¿Quién es esa persona?"),
  ("dónde", "где / куда", "¿Dónde vives?"),
  ("cuándo", "когда", "¿Cuándo empieza la clase?"),
  ("cuánto", "сколько", "¿Cuánto cuesta este libro?"),
  ("por qué", "почему", "¿Por qué estudias español?"),
  ("porque", "потому что", "Porque me gusta mucho el idioma."),
  ("mucho", "много / очень", "Me gusta mucho viajar."),
  ("poco", "мало / немного", "Hablo un poco de español."),
  ("hombre", "мужчина", "El hombre lee un libro."),
  ("mujer", "женщина / жена", "La mujer habla con el doctor."),
  ("chico", "мальчик / парень", "El chico juega al fútbol."),
  ("chica", "девочка / девушка", "La chica es muy simpática."),
  ("niño", "ребенок / мальчик", "El niño duerme en su cama."),
  ("niña", "девочка", "La niña dibuja una flor."),
  ("amigo", "друг", "Juan es mi mejor amigo."),
  ("amiga", "подруга", "Mi amiga vive en Barcelona."),
  ("familia", "семья", "Tengo una familia grande."),
  ("padre", "отец / папа", "Mi padre trabaja en un banco."),
  ("madre", "мать / мама", "Mi madre cocina delicioso."),
  ("padres", "родители", "Mis padres viven en el campo."),
  ("hijo", "сын", "Mi hijo tiene diez años."),
  ("hija", "дочь", "Su hija estudia medicina."),
  ("hermano", "брат", "Mi hermano mayor vive en Madrid."),
  ("hermana", "сестра", "Tengo una hermana menor."),
  ("abuelo", "дедушка", "Mi abuelo cuenta historias lindas."),
  ("abuela", "бабушка", "Mi abuela hace tortas ricas."),
  ("tío", "дядя", "Mi tío es ingeniero."),
  ("tía", "тетя", "Mi tía enseña inglés."),
  ("primo", "двоюродный брат", "Juego con mi primo los domingos."),
  ("prima", "двоюродная сестра", "Mi prima vive cerca de acá."),
  ("esposo", "муж", "Mi esposo es cocinero."),
  ("esposa", "жена", "Su esposa es médica."),
  ("persona", "человек / персона", "Es una persona muy amable."),
  ("ser", "быть / являться (постоянно)", "Soy estudiante de idiomas."),
  ("estar", "находиться / быть (состояние)", "Estoy muy contento hoy."),
  ("tener", "иметь / обладать", "Tengo veinticinco años."),
  ("haber", "иметься (hay = есть)", "Hay un parque cerca de casa."),
  ("hacer", "делать", "¿Qué haces los fines de semana?"),
  ("ir", "идти / ехать", "Voy al trabajo en metro."),
  ("venir", "приходить / приезжать", "¿A qué hora vienes a casa?"),
  ("ver", "видеть / смотреть", "Veo una película interesante."),
  ("mirar", "смотреть (внимательно)", "Miro fotos de mis vacaciones."),
  ("oír", "слышать", "No oigo nada con este ruido."),
  ("escuchar", "слушать", "Escucho música mientras estudio."),
  ("hablar", "говорить", "Hablo tres idiomas."),
  ("decir", "сказать / говорить", "¿Qué quieres decir con eso?"),
  ("comer", "есть / кушать", "Como con mi familia a las dos."),
  ("beber", "пить", "Bebo agua todos los días."),
  ("tomar", "брать / пить / принимать", "Tomo café por la mañana."),
  ("vivir", "жить", "Vivo en un departamento céntrico."),
  ("trabajar", "работать", "Trabajo en una oficina moderna."),
  ("estudiar", "учиться / изучать", "Estudio español todos los días."),
  ("aprender", "учить (что-то) / узнавать", "Quiero aprender a bailar tango."),
  ("comprender", "понимать", "Comprendo casi todo lo que dice."),
  ("entender", "понимать", "No entiendo esta palabra."),
  ("saber", "знать (факты, информацию)", "No sé la respuesta correcta."),
  ("conocer", "знать (человека, город)", "Conozco bien esta ciudad."),
  ("querer", "хотеть / любить", "Quiero un café caliente."),
  ("poder", "мочь / иметь возможность", "¿Puedo hacer una pregunta?"),
  ("poner", "класть / ставить", "Pongo el libro en la mesa."),
  ("dar", "давать", "Me das la cuenta, por favor."),
  ("llevar", "носить / везти / брать с собой", "Llevo una camisa blanca."),
  ("traer", "приносить", "¿Me traes un vaso de agua?"),
  ("comprar", "покупать", "Compro pan en la panadería."),
  ("vender", "продавать", "Venden frutas muy frescas aquí."),
  ("pagar", "платить", "¿Puedo pagar con tarjeta?"),
  ("costar", "стоить", "El café cuesta dos euros."),
  ("abrir", "открывать", "Abro la ventana porque hace calor."),
  ("cerrar", "закрывать", "Cierra la puerta, por favor."),
  ("empezar", "начинать", "La clase empieza a las nueve."),
  ("terminar", "заканчивать", "Termino de trabajar a las seis."),
  ("buscar", "искать", "Busco mis llaves en la mesa."),
  ("encontrar", "находить", "No encuentro mi pasaporte."),
  ("esperar", "ждать / надеяться", "Espero el autobús diez minutos."),
  ("llegar", "прибывать / приходить", "El tren llega a las ocho."),
  ("salir", "выходить / уходить", "Salgo con mis amigos hoy."),
  ("entrar", "входить", "Entramos al restaurante."),
  ("preguntar", "спрашивать", "Quiero preguntar una cosa."),
  ("responder", "отвечать", "El profesor responde la duda."),
  ("escribir", "писать", "Escribo una carta a mi amigo."),
  ("leer", "читать", "Leo las noticias por la mañana."),
  ("ayudar", "помогать", "¿Me puedes ayudar un momento?"),
  ("gustar", "нравиться", "Me gusta mucho la música latina."),
  ("casa", "дом", "Mi casa es muy cómoda."),
  ("departamento", "квартира", "Alquilo un departamento lindo."),
  ("habitación", "комната / номер", "La habitación tiene ventana."),
  ("cocina", "кухня", "La cocina está limpia."),
  ("baño", "ванная комната / туалет", "¿Dónde queda el baño?"),
  ("dormitorio", "спальня", "Mi dormitorio es tranquilo."),
  ("sala", "гостиная", "Miramos televisión en la sala."),
  ("puerta", "дверь", "La puerta principal es verde."),
  ("ventana", "окно", "Abro la ventana para ventilar."),
  ("mesa", "стол", "Pon los platos en la mesa."),
  ("silla", "стул", "Esta silla es muy cómoda."),
  ("cama", "кровать", "La cama es grande."),
  ("calle", "улица", "Vivo en una calle con árboles."),
  ("avenida", "проспект", "La avenida es muy ancha."),
  ("plaza", "площадь", "Nos vemos en la plaza central."),
  ("parque", "парк", "Camino por el parque a la tarde."),
  ("ciudad", "город", "Madrid es una ciudad hermosa."),
  ("país", "страна", "España es un gran país."),
  ("pueblo", "поселок / деревня", "Nací en un pueblo pequeño."),
  ("edificio", "здание", "Trabajo en un edificio alto."),
  ("tienda", "магазин", "La tienda abre temprano."),
  ("supermercado", "супермаркет", "Hago las compras en el supermercado."),
  ("mercado", "рынок", "Compro verduras en el mercado."),
  ("banco", "банк / скамейка", "El banco está en la esquina."),
  ("hospital", "больница", "El hospital está cerca."),
  ("comida", "еда", "La comida mexicana es sabrosa."),
  ("agua", "вода", "Bebo dos litros de agua al día."),
  ("pan", "хлеб", "Compro pan caliente."),
  ("café", "кофе", "Tomo café solo sin azúcar."),
  ("té", "чай", "Prefiero té con limón."),
  ("leche", "молоко", "Quiero un café con leche."),
  ("azúcar", "сахар", "No le pongo azúcar al café."),
  ("sal", "соль", "¿Me pasas la sal, por favor?"),
  ("aceite", "растительное масло", "Uso aceite de oliva virgen."),
  ("carne", "мясо", "El asado de carne es típico."),
  ("pollo", "курица", "Hoy cocino pollo al horno."),
  ("pescado", "рыба (приготовленная)", "El pescado está muy fresco."),
  ("huevo", "яйцо", "Desayuno dos huevos revueltos."),
  ("queso", "сыр", "Me encanta el queso con pan."),
  ("arroz", "рис", "Hago arroz con verduras."),
  ("pasta", "макароны / паста", "Los domingos comemos pasta."),
  ("fruta", "фрукты", "Como fruta todos los días."),
  ("manzana", "яблоко", "Compré manzanas rojas."),
  ("banana", "банан", "La banana tiene potasio."),
  ("naranja", "апельсин", "Bebo jugo de naranja natural."),
  ("ensalada", "салат", "Pido una ensalada mixta."),
  ("tomate", "помидор", "El tomate está maduro."),
  ("papa", "картофель", "Me gustan las papas fritas."),
  ("vino", "вино", "Tomamos una copa de vino tinto."),
  ("cerveza", "пиво", "Una cerveza bien fría, por favor."),
  ("tiempo", "время / погода", "No tengo mucho tiempo libre."),
  ("hora", "час / время", "¿Qué hora tienes?"),
  ("minuto", "минута", "Llego en cinco minutos."),
  ("segundo", "секунда", "Espera un segundo, por favor."),
  ("día", "день", "Hoy es un día soleado."),
  ("noche", "ночь / вечер", "Trabajo de noche a veces."),
  ("mañana", "утро / завтра", "Nos vemos mañana a las diez."),
  ("tarde", "день (после полудня) / поздно", "Buenas tardes a todos."),
  ("semana", "неделя", "La semana pasa muy rápido."),
  ("mes", "месяц", "En un mes viajo a Argentina."),
  ("año", "год", "Tengo 28 años de edad."),
  ("hoy", "сегодня", "Hoy no trabajo."),
  ("ayer", "вчера", "Ayer fue un día largo."),
  ("ahora", "сейчас", "Ahora estoy estudiando."),
  ("lunes", "понедельник", "El lunes empiezo el gimnasio."),
  ("martes", "вторник", "El martes tengo reunión."),
  ("miércoles", "среда", "Los miércoles estudio español."),
  ("jueves", "четверг", "El jueves ceno con amigos."),
  ("viernes", "пятница", "¡Por fin es viernes!"),
  ("sábado", "суббота", "El sábado duermo hasta tarde."),
  ("domingo", "воскресенье", "El domingo almuerzo en familia."),
  ("uno", "один", "Tengo un hermano."),
  ("dos", "два", "Son las dos de la tarde."),
  ("tres", "три", "Tres amigos vienen hoy."),
  ("cuatro", "четыре", "Hay cuatro sillas en la mesa."),
  ("cinco", "пять", "Compré cinco manzanas."),
  ("seis", "шесть", "El tren sale a las seis."),
  ("siete", "семь", "Trabajo siete horas."),
  ("ocho", "восемь", "Duermo ocho horas."),
  ("nueve", "девять", "Llego a las nueve."),
  ("diez", "десять", "Cuesta diez pesos."),
  ("veinte", "двадцать", "Son veinte euros en total."),
  ("cincuenta", "пятьдесят", "Tiene cincuenta páginas."),
  ("cien", "сто", "Hay cien personas aquí."),
  ("mil", "тысяча", "Cuesta mil pesos."),
  ("primero", "первый", "Es mi primer viaje a España."),
  ("último", "последний", "Es el último tren de la noche."),
  ("bueno", "хороший", "Es un muy buen profesor."),
  ("malo", "плохой", "El clima está malo hoy."),
  ("grande", "большой", "Tienen un auto grande."),
  ("pequeño", "маленький", "Es un pueblo pequeño."),
  ("nuevo", "новый", "Compré un teléfono nuevo."),
  ("viejo", "старый", "Es un edificio viejo y lindo."),
  ("joven", "молодой", "Es un profesor joven."),
  ("fácil", "легкий / простой", "El español es fácil al inicio."),
  ("difícil", "трудный / сложный", "Este ejercicio es difícil."),
  ("rápido", "быстрый / быстро", "El tren es muy rápido."),
  ("lento", "медленный / медленно", "El internet está lento."),
  ("caro", "дорогой (по цене)", "Este restaurante es caro."),
  ("barato", "дешевый", "La comida es rica y barata."),
  ("blanco", "белый", "Lleva una camisa blanca."),
  ("negro", "черный", "Tengo un gato negro."),
  ("rojo", "красный", "El auto rojo es de Juan."),
  ("azul", "синий / голубой", "El cielo está azul despejado."),
  ("verde", "зеленый", "El parque está muy verde."),
  ("amarillo", "желтый", "El taxi es amarillo y negro."),
  ("marrón", "коричневый", "Lleva zapatos marrones."),
  ("gris", "серый", "El día está nublado y gris."),
  ("ropa", "одежда", "Compré ropa para el verano."),
  ("camisa", "рубашка", "Planché mi camisa blanca."),
  ("remera", "футболка (LatAm)", "Uso una remera cómoda."),
  ("camiseta", "футболка (España)", "Compré una camiseta de fútbol."),
  ("pantalón", "брюки / штаны", "Este pantalón me queda bien."),
  ("vestido", "платье", "Lleva un vestido elegante."),
  ("falda", "юбка", "La falda es de color azul."),
  ("zapatos", "обувь / туфли", "Estos zapatos son cómodos."),
  ("zapatillas", "кроссовки", "Corro con zapatillas nuevas."),
  ("abrigo", "пальто / теплая куртка", "Ponte el abrigo que hace frío."),
  ("chaqueta", "куртка / пиджак", "Dejé mi chaqueta en la silla."),
  ("sombrero", "шляпа", "Uso sombrero en la playa."),
  ("bolso", "сумка", "Lleva un bolso de cuero."),
  ("mochila", "рюкзак", "Puse los libros en la mochila."),
  ("gafas", "очки", "No puedo leer sin mis gafas."),
  ("reloj", "часы", "Miro la hora en mi reloj."),
  ("llave", "ключ", "No encuentro las llaves de casa."),
  ("viaje", "путешествие / поездка", "¡Buen viaje a España!"),
  ("viajar", "путешествовать", "Me encanta viajar en tren."),
  ("auto", "автомобиль (LatAm)", "Vamos en auto al lago."),
  ("coche", "машина (España)", "El coche está en el garage."),
  ("autobús", "автобус", "Tomo el autobús número diez."),
  ("colectivo", "автобус (Argentina)", "El colectivo pasa cada cinco minutos."),
  ("metro", "метро", "El metro es muy rápido."),
  ("tren", "поезд", "El tren llega a horario."),
  ("avión", "самолет", "El avión aterriza a las tres."),
  ("aeropuerto", "аэропорт", "Vamos al aeropuerto en taxi."),
  ("estación", "станция / вокзал", "Nos encontramos en la estación."),
  ("parada", "остановка", "La parada de bus está enfrente."),
  ("boleto", "билет", "Compré dos boletos de cine."),
  ("billete", "билет (España)", "Un billete de ida y vuelta."),
  ("pasaporte", "загранпаспорт", "Muestro mi pasaporte en la aduana."),
  ("maleta", "чемодан", "Preparo mi maleta para viajar."),
  ("hotel", "отель / гостиница", "El hotel tiene vista al mar."),
  ("playa", "пляж", "Pasamos el día en la playa."),
  ("mar", "море", "El agua del mar está tibia."),
  ("sol", "солнце", "El sol brilla fuerte hoy."),
  ("luna", "луна", "La luna está llena esta noche."),
  ("río", "река", "El río cruza toda la ciudad."),
  ("montaña", "гора", "Caminamos por la montaña."),
  ("campo", "поле / деревня", "Paso las vacaciones en el campo."),
  ("árbol", "дерево", "Hay muchos árboles en el parque."),
  ("y", "и", "Hablo español e inglés."),
  ("o", "или", "¿Prefieres té o café?"),
  ("pero", "но", "Quiero ir, pero no puedo."),
  ("también", "тоже / также", "Yo también estudio medicina."),
  ("tampoco", "также не / тоже не", "Yo tampoco sé la respuesta."),
  ("siempre", "всегда", "Siempre llego puntual."),
  ("nunca", "никогда", "Nunca tomo café de noche."),
  ("a veces", "иногда", "A veces voy al cine solo."),
  ("casi", "почти", "Ya casi terminamos la lección."),
  ("aquí", "здесь", "Mi amigo vive aquí."),
  ("ahí", "там (рядом)", "El libro está ahí en la mesa."),
  ("allí", "вон там (далеко)", "El banco queda allí lejos."),
  ("cerca", "близко / рядом", "La farmacia está muy cerca."),
  ("lejos", "далеко", "El aeropuerto queda lejos."),
  ("dentro", "внутри", "Las llaves están dentro del bolso."),
  ("fuera", "снаружи", "Hace mucho frío afuera."),
  ("arriba", "вверху / наверху", "El departamento está arriba."),
  ("abajo", "внизу", "Esperamos abajo en la puerta."),
  ("delante", "впереди / перед", "El auto está delante de casa."),
  ("detrás", "сзади / за", "El jardín queda detrás."),
  ("derecha", "право / направо", "Gira a la derecha en la esquina."),
  ("izquierda", "лево / налево", "La tienda queda a la izquierda."),
  ("todo", "всё / весь", "Todo está muy claro, gracias."),
  ("nada", "ничего", "No pasa nada, tranquilo."),
  ("algo", "что-то / немного", "¿Quieres tomar algo caliente?"),
  ("alguien", "кто-то", "¿Hay alguien en casa?"),
  ("nadie", "никто", "No hay nadie en la oficina."),
  ("mismo", "тот же самый", "Tenemos el mismo profesor."),
  ("otro", "другой", "Quiero probar otro plato."),
  ("cada", "каждый", "Practico español cada día."),
  ("más", "больше / ещё", "Un poco más de agua, por favor."),
  ("menos", "меньше", "Trabajo menos horas los viernes."),
  ("muy", "очень", "Es un tema muy interesante."),
  ("bastante", "достаточно / довольно", "El examen fue bastante fácil."),
  ("demasiado", "слишком", "Hace demasiado calor afuera."),
  ("nombre", "имя", "¿Cuál es tu nombre completo?"),
  ("apellido", "фамилия", "Mi apellido es Pérez."),
  ("edad", "возраст", "¿Qué edad tienes?"),
  ("cumpleaños", "день рождения", "¡Feliz cumpleaños, amigo!"),
  ("fiesta", "праздник / вечеринка", "El sábado hay una gran fiesta."),
  ("música", "музыка", "Me gusta escuchar música latina."),
  ("película", "фильм", "Vimos una película divertida."),
  ("libro", "книга", "Leo un libro en español."),
  ("foto", "фотография", "Tomé muchas fotos del viaje."),
  ("teléfono", "телефон", "Mi número de teléfono es nuevo."),
  ("mensaje", "сообщение", "Te mandé un mensaje por WhatsApp."),
  ("número", "номер / число", "¿Cuál es tu número de puerta?"),
  ("calor", "жара / тепло", "Tengo mucho calor hoy."),
  ("frío", "холод", "Tengo frío, cierra la ventana."),
  ("suerte", "удача", "¡Mucha suerte en tu examen!")
]

# -*- coding: utf-8 -*-
import json

# Build A2 (500 words)
a2_raw = [
  # Daily Routine & Reflexives (1-50)
  ("despertarse", "просыпаться", "Me despierto a las siete de la mañana."),
  ("levantarse", "вставать (с постели)", "Me levanto enseguida después de despertar."),
  ("ducharse", "принимать душ", "Me ducho con agua tibia todos los días."),
  ("bañarse", "купаться / принимать ванну", "Los niños se bañan por la noche."),
  ("lavarse", "умываться / мыть себе", "Me lavo las manos antes de comer."),
  ("cepillarse", "чистить (зубы, волосы)", "Me cepillo los dientes tres veces al día."),
  ("peinarse", "причесываться", "Se peina frente al espejo."),
  ("afeitarse", "бриться", "Mi padre se afeita por la mañana."),
  ("maquillarse", "краситься / наносить макияж", "Ella se maquilla antes de salir."),
  ("vestirse", "одеваться", "Me visto rápido para no llegar tarde."),
  ("desvestirse", "раздеваться", "Se desviste antes de dormir."),
  ("ponerse", "надевать (на себя)", "Me pongo una campera abrigada."),
  ("quitarse", "снимать (с себя одежду)", "Me quito los zapatos al entrar."),
  ("acostarse", "ложиться спать", "Me acuesto a las once de la noche."),
  ("dormirse", "засыпать", "Me duermo muy rápido cuando estoy cansado."),
  ("desayunar", "завтракать", "Desayuno tostadas con café."),
  ("almorzar", "обедать", "Almorzamos en el comedor del trabajo."),
  ("cenar", "ужинать", "Cenamos liviano por la noche."),
  ("merendar", "полдничать / перекусывать", "Meriendo un té con galletitas."),
  ("cocinar", "готовить еду", "Me encanta cocinar platos típicos."),
  ("limpiar", "убирать / чистить", "Limpio la casa los sábados."),
  ("ordenar", "наводить порядок", "Ordeno mi escritorio antes de empezar."),
  ("lavar", "мыть / стирать", "Lavo la ropa en el lavarropas."),
  ("planchar", "гладить (одежду)", "No me gusta planchar camisas."),
  ("barrer", "подметать", "Barro el piso de la cocina."),
  ("sacar la basura", "выносить мусор", "Saco la basura por la noche."),
  ("hacer la cama", "заправлять кровать", "Hago la cama todas las mañanas."),
  ("descansar", "отдыхать", "Necesito descansar un poco."),
  ("relajarse", "расслабляться", "Me relajo escuchando música suave."),
  ("pasear", "гулять", "Paseo al perro por el parque."),
  ("caminar", "ходить пешком", "Camino treinta minutos al día."),
  ("correr", "бегать", "Corro por la costanera los domingos."),
  ("entrenar", "тренироваться", "Entreno en el gimnasio tres veces por semana."),
  ("nadar", "плавать", "Me gusta nadar en la piscina."),
  ("bailar", "танцевать", "Bailamos salsa los fines de semana."),
  ("cantar", "петь", "Canta muy bien en la ducha."),
  ("tocar", "играть (на инструменте) / трогать", "Toco la guitarra desde chico."),
  ("jugar", "играть (в игры/спорт)", "Juego al fútbol con amigos."),
  ("ganar", "выигрывать / зарабатывать", "Nuestro equipo ganó el partido."),
  ("perder", "терять / проигрывать", "Perdí las llaves de casa."),
  ("olvidar", "забывать", "Olvidé comprar leche en el súper."),
  ("recordar", "помнить / вспоминать", "No recuerdo su número de teléfono."),
  ("acordarse", "вспоминать", "Me acuerdo de nuestras vacaciones."),
  ("pensar", "думать", "Pienso que es una gran idea."),
  ("creer", "верить / полагать", "Creo que va a llover hoy."),
  ("opinar", "высказывать мнение", "¿Qué opinas de este proyecto?"),
  ("parecer", "казаться", "Me parece muy bien."),
  ("sentirse", "чувствовать себя", "Me siento muy feliz hoy."),
  ("preocuparse", "беспокоиться", "No te preocupes por nada."),
  ("divertirse", "веселиться / развлекаться", "Nos divertimos mucho en la fiesta."),

  # Health, Body & Feelings (51-100)
  ("cuerpo", "тело", "El ejercicio es bueno para el cuerpo."),
  ("cabeza", "голова", "Me duele mucho la cabeza."),
  ("ojo", "глаз", "Tiene ojos marrones hermosos."),
  ("oreja", "ухо", "Me duelen las orejas con el viento."),
  ("nariz", "нос", "Tengo la nariz tapada por el resfriado."),
  ("boca", "рот", "Abre la boca, por favor."),
  ("diente", "зуб", "Voy al dentista por un dolor de muela."),
  ("lengua", "язык (орган / язык)", "El español es una lengua rica."),
  ("cuello", "шея", "Tengo dolor de cuello por la mala postura."),
  ("espalda", "спина", "Me duele la espalda de estar sentado."),
  ("pecho", "грудь", "Siento opresión en el pecho."),
  ("brazo", "рука (от плеча до кисти)", "Me lastimé el brazo jugando."),
  ("mano", "рука (кисть)", "Dame la mano para cruzar."),
  ("dedo", "палец", "Me corté el dedo con papel."),
  ("pierna", "нога (выше ступни)", "Tengo las piernas cansadas."),
  ("rodilla", "колено", "Me operaron de la rodilla."),
  ("pie", "нога (стопа)", "Voy a pie al trabajo."),
  ("corazón", "сердце", "El corazón late con fuerza."),
  ("estómago", "желудок / живот", "Me duele el estómago por la comida."),
  ("piel", "кожа", "Uso protector solar en la piel."),
  ("salud", "здоровье", "¡Salud y prosperidad!"),
  ("enfermedad", "болезнь", "Es una enfermedad leve."),
  ("enfermo", "больной", "Hoy no voy a trabajar porque estoy enfermo."),
  ("sano", "здоровый", "Como comida sana y equilibrada."),
  ("dolor", "боль", "Tengo un dolor fuerte aquí."),
  ("doler", "болеть (о части тела)", "¿Qué te duele exactamente?"),
  ("fiebre", "температура / жар", "El niño tiene 38 de fiebre."),
  ("gripe", "грипп", "Tengo gripe y debo guardar cama."),
  ("tos", "кашель", "Tomo jarabe para la tos."),
  ("resfriado", "простуда", "Tengo un resfriado común."),
  ("médico", "врач", "Tengo turno con el médico a las cuatro."),
  ("doctor", "доктор", "El doctor me recetó reposo."),
  ("enfermero", "медбрат / медсестра", "La enfermera me puso la vacuna."),
  ("farmacia", "аптека", "Compro los remedios en la farmacia."),
  ("medicamento", "лекарство", "Tomo el medicamento después de comer."),
  ("remedio", "лекарство / средство (LatAm)", "Este té es un buen remedio."),
  ("pastilla", "таблетка", "Toma una pastilla cada ocho horas."),
  ("receta", "рецепт (медицинский/кулинарный)", "El médico me dio una receta."),
  ("cita", "запись / свидание / встреча", "Tengo cita en el consultorio."),
  ("turno", "очередь / талон / запись (LatAm)", "Saqué turno por internet."),
  ("alegre", "радостный", "Es una persona muy alegre."),
  ("triste", "грустный", "Está triste porque extraña a su familia."),
  ("cansado", "уставший", "Estoy agotado y cansado."),
  ("enojado", "сердитый / злой", "Está enojado por el retraso."),
  ("nervioso", "нервный / взволнованный", "Estoy nervioso por el examen."),
  ("tranquilo", "спокойный", "Es un lugar muy tranquilo."),
  ("asustado", "напуганный", "El perro está asustado por los truenos."),
  ("sorprendido", "удивленный", "Quedé sorprendido con la noticia."),
  ("aburrido", "скучающий / скучный", "La película fue muy aburrida."),
  ("contento", "довольный", "Estoy muy contento con los resultados."),

  # City, Navigation & Shopping (101-150)
  ("barrio", "район / квартал", "Vivo en un barrio muy seguro."),
  ("centro", "центр города", "Voy al centro a hacer trámites."),
  ("esquina", "угол (улицы)", "Nos encontramos en la esquina."),
  ("cruce", "перекресток", "Ten cuidado en el cruce de calles."),
  ("semáforo", "светофор", "Espera a que el semáforo esté en verde."),
  ("paso de peatones", "пешеходный переход", "Cruza por el paso de peatones."),
  ("acera", "тротуар (España)", "Camina por la acera."),
  ("vereda", "тротуар (Argentina)", "Arreglaron la vereda de mi cuadra."),
  ("puente", "мост", "Cruzamos el puente sobre el río."),
  ("carretera", "шоссе / трасса", "La carretera está en buen estado."),
  ("autopista", "автомагистраль", "Vamos más rápido por la autopista."),
  ("estacionamiento", "парковка", "Dejé el auto en el estacionamiento."),
  ("gasolinera", "заправка", "Cargo combustible en la gasolinera."),
  ("museo", "музей", "El museo de arte abre los domingos."),
  ("teatro", "театр", "Compré entradas para el teatro."),
  ("cine", "кинотеатр", "Vamos al cine a ver el estreno."),
  ("biblioteca", "библиотека", "Estudio en silencio en la biblioteca."),
  ("iglesia", "церковь", "La iglesia antigua está en la plaza."),
  ("comisaría", "полицейский участок", "Hice la denuncia en la comisaría."),
  ("correo", "почта", "Envío un paquete por correo."),
  ("banco", "банк", "El banco atiende hasta las tres."),
  ("cajero automático", "банкомат", "Saco dinero del cajero automático."),
  ("tarjeta de crédito", "кредитная карта", "¿Aceptan tarjeta de crédito?"),
  ("efectivo", "наличные", "Pago en efectivo."),
  ("moneda", "монета / валюта", "No tengo monedas para la máquina."),
  ("billete", "купюра / билет", "Un billete de cien pesos."),
  ("cambio", "сдача / обмен валюты", "Quédese con el cambio."),
  ("precio", "цена", "El precio incluye impuestos."),
  ("descuento", "скидка", "Hay un veinte por ciento de descuento."),
  ("oferta", "акция / предложение", "Esta camisa está en oferta."),
  ("recibo", "чек / квитанция", "¿Me da el recibo de compra?"),
  ("bolsa", "пакет / сумка", "¿Necesita una bolsa de plástico?"),
  ("cliente", "клиент / покупатель", "El cliente siempre tiene razón."),
  ("vendedor", "продавец", "El vendedor me atendió muy bien."),
  ("probar", "мерить / пробовать", "¿Puedo probarme este saco?"),
  ("probador", "примерочная", "El probador está al fondo."),
  ("talla", "размер одежды (España)", "¿Qué talla de camisa usa?"),
  ("talle", "размер одежды (LatAm)", "¿Tiene este pantalón en talle 40?"),
  ("número de calzado", "размер обуви", "Calzo número 42."),
  ("quedar bien", "сидеть хорошо (об одежде)", "Este vestido te queda perfecto."),
  ("apretado", "тесный / узкий", "Estos zapatos me quedan apretados."),
  ("suelto", "свободный / широкий", "Prefiero ropa suelta en verano."),
  ("caro", "дорогой", "Es un producto muy caro."),
  ("barato", "дешевый", "Conseguí un pasaje muy barato."),
  ("gratis", "бесплатно", "La entrada al museo es gratis."),
  ("calidad", "качество", "Es una tela de excelente calidad."),
  ("garantía", "гарантия", "El electrodoméstico tiene un año de garantía."),
  ("devolver", "возвращать (вещь)", "Quiero devolver este artículo."),
  ("cambiar", "менять / обменивать", "¿Puedo cambiarlo por otro color?"),
  ("abierto", "открыто", "La tienda está abierta."),

  # Past Events & Time Markers (151-200)
  ("anoche", "вчера вечером", "Anoche salí a cenar."),
  ("anteayer", "позавчера", "Anteayer llovió todo el día."),
  ("la semana pasada", "на прошлой неделе", "La semana pasada rendí un examen."),
  ("el mes pasado", "в прошлом месяце", "El mes pasado viajé a Córdoba."),
  ("el año pasado", "в прошлом году", "El año pasado terminé la carrera."),
  ("hace poco", "недавно", "Llegué a la ciudad hace poco."),
  ("hace mucho", "давно", "No veo a mi amigo hace mucho tiempo."),
  ("ya", "уже", "Ya terminé todos mis deberes."),
  ("todavía no", "еще нет", "Todavía no recibí el paquete."),
  ("aún", "все еще / еще", "Aún tengo dudas con el pretérito."),
  ("pronto", "скоро", "Nos vemos muy pronto."),
  ("luego", "потом / затем", "Almuerzo y luego sigo trabajando."),
  ("después", "после / позже", "Te llamo después de la reunión."),
  ("antes", "до / раньше", "Antes vivía en un pueblo pequeño."),
  ("durante", "во время / в течение", "Durante el verano viajo mucho."),
  ("mientras", "в то время как / пока", "Leo mientras espero el colectivo."),
  ("entonces", "тогда / в таком случае", "Si no puedes venir, entonces voy yo."),
  ("de repente", "вдруг / внезапно", "De repente se apagó la luz."),
  ("por fin", "наконец-то", "¡Por fin conseguí el pasaporte!"),
  ("al final", "в конце концов", "Al final decidimos no viajar."),
  ("enseguida", "сейчас же / немедленно", "Vuelvo enseguida, espérame."),
  ("temprano", "рано", "Me levanto muy temprano."),
  ("tarde", "поздно", "Llegué tarde por el tránsito."),
  ("puntual", "пунктуальный", "Siempre es muy puntual."),
  ("demora", "задержка", "El vuelo tiene una hora de demora."),
  ("horario", "расписание", "¿Cuál es el horario de atención?"),
  ("calendario", "календарь", "Miro la fecha en el calendario."),
  ("fecha", "дата", "¿Qué fecha es hoy?"),
  ("estación del año", "время года / сезон", "El otoño es mi estación favorita."),
  ("primavera", "весна", "En primavera florecen los árboles."),
  ("verano", "лето", "En verano hace mucho calor."),
  ("otoño", "осень", "En otoño caen las hojas."),
  ("invierno", "зима", "En invierno nieva en la cordillera."),
  ("clima", "климат / погода", "El clima es templado y agradable."),
  ("temperatura", "температура воздуха", "Hoy la temperatura es de 25 grados."),
  ("grado", "градус", "Hacen treinta grados a la sombra."),
  ("lluvia", "дождь", "La lluvia refrescó el ambiente."),
  ("llover", "идти (о дожде)", "Está lloviendo torrencialmente."),
  ("nieve", "снег", "Hay mucha nieve en la montaña."),
  ("nevar", "идти (о снеге)", "Nieva en Bariloche."),
  ("viento", "ветер", "Corre un viento muy fuerte."),
  ("nube", "облако", "No hay ni una nube en el cielo."),
  ("nublado", "пасмурно / облачно", "El cielo está totalmente nublado."),
  ("despejado", "ясно / безоблачно", "El día está soleado y despejado."),
  ("tormenta", "гроза / буря", "Viene una tormenta eléctrica."),
  ("trueno", "гром", "Se escuchó un trueno fuerte."),
  ("relámpago", "молния", "El relámpago iluminó la noche."),
  ("humedad", "влажность", "Hay mucha humedad en Buenos Aires."),
  ("pronóstico", "прогноз погоды", "El pronóstico anuncia sol para el fin de semana."),
  ("paraguas", "зонт", "Lleva paraguas por si llueve.")
]

# Additional 300 words for A2 to reach 500
a2_extra = [
  # House & Appliances (201-250)
  ("electrodoméstico", "бытовая техника", "Compré un electrodoméstico nuevo."),
  ("heladera", "холодильник (LatAm)", "Guarda la leche en la heladera."),
  ("frigorífico", "холодильник (España)", "El frigorífico no enfría bien."),
  ("lavarropas", "стиральная машина (LatAm)", "Puse el lavarropas a funcionar."),
  ("lavadora", "стиральная машина (España)", "La lavadora centrifugó la ropa."),
  ("microondas", "микроволновка", "Caliento la sopa en el microondas."),
  ("horno", "духовка / печь", "El pastel está en el horno."),
  ("hornalla", "конфорка (LatAm)", "Apaga la hornalla de la cocina."),
  ("fuego", "огонь", "Enciende el fuego para cocinar."),
  ("plato", "тарелка / блюдо", "Pon los platos hondos en la mesa."),
  ("vaso", "стакан", "Un vaso de jugo de naranja."),
  ("taza", "чашка / кружка", "Tomo café en una taza grande."),
  ("copa", "бокал / рюмка", "Brindamos con una copa de vino."),
  ("cubiertos", "столовые приборы", "Pon los cubiertos en la mesa."),
  ("cuchillo", "нож", "Este cuchillo corta muy bien."),
  ("tenedor", "вилка", "Como los fideos con tenedor."),
  ("cuchara", "ложка", "Tomo la sopa con cuchara."),
  ("cucharita", "чайная ложка", "¿Me das una cucharita para el azúcar?"),
  ("sartén", "сковорода", "Hago huevos en la sartén."),
  ("olla", "кастрюля", "Puse agua a hervir en la olla."),
  ("servilleta", "салфетка", "Pásame una servilleta de papel."),
  ("mantel", "скатерть", "Puse un mantel limpio."),
  ("almohada", "подушка", "Esta almohada es muy suave."),
  ("sábana", "простыня", "Cambié las sábanas de la cama."),
  ("frazada", "одеяло (LatAm)", "Tengo frío, tráeme una frazada."),
  ("manta", "плед / одеяло", "Me tapé con una manta en el sillón."),
  ("sillón", "кресло / диван", "Miro la tele sentado en el sillón."),
  ("sofá", "диван", "El sofá es muy amplio."),
  ("alfombra", "ковер", "La alfombra del living es suave."),
  ("cortina", "штора / занавеска", "Abre las cortinas para que entre luz."),
  ("espejo", "зеркало", "Me miro en el espejo."),
  ("armario", "шкаф для одежды", "Guardo la ropa en el armario."),
  ("placard", "встроенный шкаф (LatAm)", "El placard tiene estantes amplios."),
  ("cajón", "выдвижной ящик", "Las medias están en el primer cajón."),
  ("llave de paso", "кран", "Cierra la llave de paso de agua."),
  ("grifo", "кран (España)", "El grifo del lavamanos gotea."),
  ("canilla", "кран (Argentina)", "La canilla de la cocina es monocomando."),
  ("inodoro", "унитаз", "El inodoro está limpio."),
  ("ducha", "душ", "La ducha sale bien caliente."),
  ("toalla", "полотенце", "Secate las manos con la toalla."),
  ("jabón", "мыло", "Lávate con agua y jabón."),
  ("champú", "шампунь", "Compré champú para cabello seco."),
  ("pasta dental", "зубная паста", "Se terminó la pasta dental."),
  ("cepillo de dientes", "зубная щетка", "Cambio mi cepillo cada tres meses."),
  ("papel higiénico", "туалетная бумага", "Compré un paquete de papel higiénico."),
  ("basura", "мусор", "Tira el papel al tacho de basura."),
  ("tacho", "ведро (LatAm)", "El tacho de reciclaje es verde."),
  ("balde", "ведро", "Llené el balde con agua para limpiar."),
  ("trapo", "тряпка", "Pasa el trapo por la mesa."),
  ("escoba", "метла", "Barrer con la escoba."),

  # Food Preparation & Supermarket (251-300)
  ("despensa", "кладовая", "Guardo las latas en la despensa."),
  ("ingrediente", "ингредиент", "Tenemos todos los ingredientes listos."),
  ("receta", "кулинарный рецепт", "Sigo la receta de mi abuela."),
  ("hervir", "кипятить / варить", "El agua ya está hirviendo."),
  ("freír", "жарить", "Frío las papas en aceite caliente."),
  ("hornear", "печь в духовке", "Horneo pan casero los domingos."),
  ("cortar", "резать", "Corta la cebolla en cubitos."),
  ("picar", "рубить / измельчать", "Pico el ajo bien fino."),
  ("mezclar", "смешивать", "Mezclo los ingredientes en un bol."),
  ("batir", "взбивать", "Bato los huevos con el azúcar."),
  ("salar", "солить", "Sala la carne a gusto."),
  ("probar", "пробовать на вкус", "Prueba la salsa a ver si le falta sal."),
  ("dulce", "сладкий", "Este postre está muy dulce."),
  ("salado", "соленый", "La sopa quedó un poco salada."),
  ("amargo", "горький", "El café sin azúcar es amargo."),
  ("ácido", "кислый", "El limón es muy ácido."),
  ("picante", "острый", "La comida mexicana tiene chile picante."),
  ("rico", "вкусный / богатый", "¡Qué rico está este plato!"),
  ("delicioso", "восхитительный", "Una cena deliciosa con amigos."),
  ("sabroso", "аппетитный / сочный", "Un asado muy sabroso."),
  ("fresco", "свежий / прохладный", "Pescado fresco del día."),
  ("caliente", "горячий", "Cuidado, la taza está muy caliente."),
  ("frío", "холодный", "Quiero un vaso de agua fría."),
  ("tibio", "теплый", "Leche tibia antes de dormir."),
  ("cebolla", "лук", "La cebolla me hace llorar."),
  ("ajo", "чеснок", "El ajo le da mucho sabor a la comida."),
  ("zanahoria", "морковь", "Rallé zanahoria para la ensalada."),
  ("lechuga", "салат (листья)", "Lavo bien las hojas de lechuga."),
  ("pepino", "огурец", "Corto pepino en rodajas."),
  ("espinaca", "шпинат", "Hago tarta de espinaca."),
  ("champiñón", "шампиньон / гриб", "Salteo champiñones con manteca."),
  ("hongo", "гриб (LatAm)", "Risotto de hongos."),
  ("manteca", "сливочное масло (LatAm)", "Unto las tostadas con manteca."),
  ("mantequilla", "сливочное масло (España)", "Mantequilla con mermelada."),
  ("mermelada", "джем / варенье", "Mermelada de frutilla casera."),
  ("dulce de leche", "вареная сгущенка (LatAm)", "Alfajor relleno de dulce de leche."),
  ("harina", "мука", "Compré un kilo de harina de trigo."),
  ("levadura", "дрожжи", "La masa necesita levadura."),
  ("vinagre", "уксус", "Condimento la ensalada con vinagre."),
  ("pimienta", "перец (приправа)", "Agrego una pizca de pimienta negra."),
  ("especias", "специи / пряности", "Compro especias en el mercado."),
  ("hierbas", "травы", "Hierbas aromáticas del jardín."),
  ("orégano", "орегано", "Le pongo orégano a la pizza."),
  ("albahaca", "базилик", "Salsa pesto con albahaca fresca."),
  ("jamón", "ветчина", "Sándwich de jamón y queso."),
  ("embutido", "колбасные изделия", "Compramos embutidos artesanales."),
  ("cerdo", "свинина", "Costillitas de cerdo al horno."),
  ("vaca", "говядина / корова", "Carne vacuna de primera calidad."),
  ("ternera", "телятина", "Milanesas de ternera."),
  ("cordero", "баранина", "Cordero patagónico asado."),

  # Travel, Hotel & Transport Details (301-350)
  ("reserva", "бронь / резервация", "Tengo una reserva a nombre de Carlos."),
  ("reservar", "бронировать", "Quiero reservar una habitación doble."),
  ("cancelar", "отменять", "Tuve que cancelar el pasaje."),
  ("confirmar", "подтверждать", "Confirmo mi asistencia por mail."),
  ("alojamiento", "жилье / размещение", "Buscamos alojamiento céntrico."),
  ("hospedarse", "останавливаться (в отеле)", "Nos hospedamos en un hotel tres estrellas."),
  ("recepción", "стойка регистрации", "Dejé la llave en la recepción."),
  ("recepcionista", "администратор отеля", "El recepcionista fue muy atento."),
  ("huésped", "гость / постоялец", "El hotel tiene muchos huéspedes."),
  ("equipaje", "багаж", "Despacho el equipaje en el mostrador."),
  ("valija", "чемодан (LatAm)", "Llevo una valija de mano."),
  ("mochila", "рюкзак", "Viajo como mochilero."),
  ("bolso de mano", "ручная кладь", "El bolso de mano va en la cabina."),
  ("aduana", "таможня", "Pasamos el control de aduana."),
  ("control de seguridad", "контроль безопасности", "Saca los líquidos en el control."),
  ("puerta de embarque", "выход на посадку", "El vuelo sale por la puerta 12."),
  ("embarcar", "садиться на борт", "Comenzamos a embarcar el avión."),
  ("despegar", "взлетать", "El avión despega puntual."),
  ("aterrizar", "приземляться", "Aterrizamos en Madrid a las ocho."),
  ("escala", "пересадка", "Vuelo directo sin escalas."),
  ("vuelo", "рейс / полет", "¿A qué hora sale tu vuelo?"),
  ("aerolínea", "авиакомпания", "Viajo con una aerolínea low-cost."),
  ("azafata", "стюардесса", "La azafata sirvió la merienda."),
  ("piloto", "пилот", "El piloto anunció turbulencias leves."),
  ("asiento", "место / сиденье", "Tengo asiento de ventanilla."),
  ("ventanilla", "окно в самолете / окошко кассы", "Prefiero asiento junto a la ventanilla."),
  ("pasillo", "проход / коридор", "Asiento de pasillo para levantarme fácil."),
  ("fila", "ряд / очередь", "Estoy en la fila cuatro."),
  ("andén", "платформа на вокзале", "El tren espera en el andén dos."),
  ("vía", "железнодорожный путь", "Cruzamos las vías con precaución."),
  ("vagón", "вагон поезда", "Mi asiento está en el tercer vagón."),
  ("conductor", "водитель", "El conductor frenó en la esquina."),
  ("chofer", "шофер (LatAm)", "El chofer del micro fue muy amable."),
  ("pasajero", "пассажир", "Todos los pasajeros deben abrocharse el cinturón."),
  ("cinturón de seguridad", "ремень безопасности", "Ponte el cinturón al subir al auto."),
  ("freno", "тормоз", "Pisé el freno de golpe."),
  ("acelerador", "педаль газа", "Presionó el acelerador en la ruta."),
  ("volante", "руль", "Toma el volante con ambas manos."),
  ("rueda", "колесо", "Tengo que cambiar una rueda pinchada."),
  ("neumático", "шина", "Revisé la presión de los neumáticos."),
  ("mapa", "карта", "Miro el mapa en el celular."),
  ("dirección", "адрес / направление", "¿Cuál es la dirección exacta?"),
  ("guía turístico", "гид / экскурсовод", "El guía explicó la historia del castillo."),
  ("excursión", "экскурсия", "Hicimos una excursión a las cataratas."),
  ("monumento", "памятник", "Visitamos los monumentos principales."),
  ("castillo", "замок", "El castillo medieval está en la colina."),
  ("catedral", "собор", "La catedral gótica es impresionante."),
  ("ruinas", "руины / развалины", "Recorrimos las ruinas mayas."),
  ("souvenir", "сувенир", "Compré recuerdos para mi familia."),
  ("recuerdo", "воспоминание / сувенир", "Guardo un hermoso recuerdo del viaje."),

  # Work, Office & Education (351-400)
  ("empleo", "работа / занятость", "Busco un nuevo empleo en tecnología."),
  ("puesto", "должность", "Conseguí el puesto de analista."),
  ("jefe", "начальник", "Hablé con mi jefe sobre las vacaciones."),
  ("colega", "коллега", "Almuerzo con mis colegas de trabajo."),
  ("compañero", "товарищ / напарник", "Mi compañero de equipo me ayudó."),
  ("reunión", "собрание / встреча", "Tengo una reunión virtual a las tres."),
  ("proyecto", "проект", "Entregamos el proyecto a tiempo."),
  ("informe", "отчет / доклад", "Redacté el informe mensual."),
  ("empresa", "компания / фирма", "Trabajo en una empresa internacional."),
  ("oficina", "офис / кабинет", "Nuestra oficina está en el piso diez."),
  ("sueldo", "зарплата", "Cobro el sueldo a fin de mes."),
  ("salario", "заработная плата", "Un salario justo y acorde al mercado."),
  ("contrato", "трудовой договор", "Firmé el contrato de trabajo."),
  ("vacaciones", "отпуск", "Tengo dos semanas de vacaciones en enero."),
  ("licencia", "больничный / отпуск по болезни", "Pedí licencia médica por gripe."),
  ("entrevista", "собеседование / интервью", "Mañana tengo una entrevista laboral."),
  ("currículum", "резюме", "Actualicé mi currículum con nuevos cursos."),
  ("experiencia", "опыт работы", "Tengo cinco años de experiencia."),
  ("habilidad", "навык / умение", "Tengo buenas habilidades de comunicación."),
  ("tarea", "задача / домашнее задание", "Completé todas las tareas del día."),
  ("computadora", "компьютер (LatAm)", "Trabajo con mi computadora portátil."),
  ("ordenador", "компьютер (España)", "El ordenador se reinició solo."),
  ("pantalla", "экран / монитор", "La pantalla tiene alta resolución."),
  ("teclado", "клавиатура", "Escribo rápido en el teclado."),
  ("ratón", "компьютерная мышь (España)", "El ratón inalámbrico no tiene pila."),
  ("mouse", "компьютерная мышь (LatAm)", "El mousepad es ergonómico."),
  ("correo electrónico", "электронная почта", "Te envié los archivos por correo electrónico."),
  ("archivo", "файл / документ", "Adjunté el archivo en el mensaje."),
  ("impresora", "принтер", "La impresora se quedó sin tinta."),
  ("imprimir", "печатать", "Imprimo los contratos para firmar."),
  ("guardar", "сохранять", "Guarda el documento antes de cerrar."),
  ("borrar", "удалять / стирать", "Borré el borrador por error."),
  ("enviar", "отправлять", "Envío el presupuesto al cliente."),
  ("recibir", "получать", "Recibí la confirmación por SMS."),
  ("descargar", "скачивать", "Descargué la aplicación en el celular."),
  ("instalar", "устанавливать", "Instalé la última actualización."),
  ("red social", "социальная сеть", "No uso mucho las redes sociales."),
  ("contraseña", "пароль", "Cambié mi contraseña por seguridad."),
  ("usuario", "пользователь", "Ingresa tu nombre de usuario."),
  ("sesión", "сеанс / аккаунт", "Cierra sesión al terminar."),
  ("universidad", "университет", "Estudié en la Universidad de Buenos Aires."),
  ("facultad", "факультет", "Voy a la facultad por la tarde."),
  ("carrera", "университетская специальность", "Elegí la carrera de abogacía."),
  ("materia", "учебный предмет (LatAm)", "Aprobé todas las materias del semestre."),
  ("asignatura", "учебный предмет (España)", "La asignatura más difícil fue historia."),
  ("examen", "экзамен", "Rindo el examen final el viernes."),
  ("aprobar", "сдать экзамен (успешно)", "Aprobé con una nota excelente."),
  ("desaprobar", "завалить экзамен / не сдать", "Tengo que recuperar la materia desaprobada."),
  ("nota", "оценка / балл", "Saqué un diez de nota."),
  ("diploma", "диплом", "Recibí mi diploma de graduación."),

  # Nature, Animals & Society (401-450)
  ("naturaleza", "природа", "Me gusta disfrutar de la naturaleza."),
  ("bosque", "лес", "Paseamos por un bosque de pinos."),
  ("selva", "джунгли / тропический лес", "La selva amazónica es inmensa."),
  ("desierto", "пустыня", "En el desierto hace frío de noche."),
  ("valle", "долина", "Un valle fértil rodeado de cerros."),
  ("lago", "озеро", "Navegamos en bote por el lago."),
  ("laguna", "лагуна / небольшое озеро", "Vimos flamencos en la laguna."),
  ("isla", "остров", "Mallorca es una isla mediterránea."),
  ("costa", "побережье / берег", "Manejamos bordeando la costa."),
  ("océano", "океан", "El océano Atlántico es profundo."),
  ("animal", "животное", "Me encantan los animales domésticos."),
  ("perro", "собака / пес", "El perro ladra cuando tocan el timbre."),
  ("gato", "кот / кошка", "El gato duerme arriba del sillón."),
  ("pájaro", "птица", "Los pájaros cantan al amanecer."),
  ("ave", "птица (вид)", "El cóndor es un ave andina."),
  ("pez", "рыба (живая)", "Hay peces de colores en el acuario."),
  ("caballo", "лошадь / конь", "Montamos a caballo en la estancia."),
  ("vaca", "корова", "La vaca da leche fresca."),
  ("oveja", "овца", "Las ovejas pastan en la pradera."),
  ("cerdo", "свинья", "Los cerdos comen maíz."),
  ("león", "лев", "El león es el rey de la selva."),
  ("tigre", "тигр", "El tigre de Bengala tiene rayas."),
  ("oso", "медведь", "Vimos un oso en el parque nacional."),
  ("lobo", "волк", "El lobo aúlla a la luna llena."),
  ("mono", "обезьяна", "Los monos trepan a los árboles."),
  ("elefante", "слон", "El elefante tiene una memoria excelente."),
  ("jirafa", "жираф", "La jirafa tiene el cuello largo."),
  ("ratón", "мышь", "El gato persigue al ratón."),
  ("insecto", "насекомое", "Hay repelente para insectos."),
  ("mosquito", "комар", "Me picó un mosquito en el brazo."),
  ("mariposa", "бабочка", "Una mariposa de colores brillantes."),
  ("abeja", "пчела", "Las abejas producen miel pura."),
  ("hormiga", "муравей", "Las hormigas trabajan en equipo."),
  ("planta", "растение", "Riego las plantas del balcón."),
  ("flor", "цветок", "Me regalaron un ramo de flores."),
  ("rosa", "роза", "Una rosa roja con espinas."),
  ("hoja", "лист дерева", "Las hojas caen en otoño."),
  ("rama", "ветка", "El pájaro se posó en la rama."),
  ("raíz", "корень", "El árbol tiene raíces profundas."),
  ("tierra", "земля / почва", "La Tierra gira alrededor del Sol."),
  ("piedra", "камень", "El camino está lleno de piedras."),
  ("arena", "песок", "Caminamos descalzos por la arena caliente."),
  ("cielo", "небо", "El cielo está teñido de naranja al atardecer."),
  ("estrella", "звезда", "Miramos las estrellas en la noche clara."),
  ("universo", "вселенная", "Los misterios del universo."),
  ("planeta", "планета", "Marte es el planeta rojo."),
  ("sociedad", "общество", "Los cambios culturales en la sociedad."),
  ("gobierno", "правительство", "Las nuevas leyes del gobierno."),
  ("ley", "закон", "Es obligatorio respetar la ley."),
  ("derecho", "право / юриспруденция", "Estudia derecho en la facultad."),

  # Communication & Idiomatic Basics (451-500)
  ("costumbre", "обычай / привычка", "Es una linda costumbre tomar mate en ronda."),
  ("tradición", "традиция", "Mantenemos las tradiciones familiares."),
  ("cultura", "культура", "Aprender un idioma es conocer su cultura."),
  ("idioma", "иностранный язык", "Aprender idiomas abre muchas puertas."),
  ("lenguaje", "речь / языковая система", "El lenguaje corporal dice mucho."),
  ("palabra", "слово", "No encuentro la palabra adecuada."),
  ("frase", "фраза / предложение", "Traduce esta frase al español."),
  ("oración", "предложение / молитва", "Escribe una oración completa con sujeto y verbo."),
  ("significado", "значение / смысл", "¿Cuál es el significado de este modismo?"),
  ("sinónimo", "синоним", "Busca un sinónimo para no repetir palabras."),
  ("antónimo", "антоним", "'Alto' y 'bajo' son antónimos."),
  ("pronunciación", "произношение", "Tienes una pronunciación muy clara."),
  ("acento", "ударение / акцент", "Tiene un marcado acento porteño."),
  ("conversación", "беседа / разговор", "Tuvimos una conversación muy amena."),
  ("diálogo", "диалог", "Practicamos el diálogo en parejas."),
  ("discusión", "спор / обсуждение", "Fue una discusión respetuosa de ideas."),
  ("acuerdo", "соглашение / согласие", "Llegamos a un acuerdo satisfactorio."),
  ("desacuerdo", "разногласие", "Estamos en desacuerdo con esa decisión."),
  ("opinión", "мнение", "Respeto tu opinión aunque no la comparta."),
  ("consejo", "совет", "Gracias por tu sabio consejo."),
  ("aconsejar", "советовать", "Te aconsejo que practiques todos los días."),
  ("recomendar", "рекомендовать", "¿Qué plato me recomiendas probar?"),
  ("sugerir", "предлагать / подсказывать", "Te sugiero que descanses antes de rendir."),
  ("prometer", "обещать", "Te prometo que voy a llegar temprano."),
  ("cumplir", "выполнять (обещание) / исполняться (о возрасте)", "Cumplo 30 años mañana."),
  ("felicitar", "поздравлять", "Te felicito por haber aprobado."),
  ("agradecer", "благодарить", "Quiero agradecerles a todos por venir."),
  ("disculparse", "извиняться", "Se disculpó por el malentendido."),
  ("saludar", "здороваться / передавать привет", "Saluda a tus padres de mi parte."),
  ("despedirse", "прощаться", "Nos despedimos con un abrazo cálido."),
  ("abrazo", "объятие", "Te mando un fuerte abrazo."),
  ("beso", "поцелуй", "Un beso grande para toda la familia."),
  ("cariño", "нежность / теплота", "Con mucho cariño para ti."),
  ("amor", "любовь", "El amor por la música nunca termina."),
  ("odio", "ненависть", "El odio no resuelve ningún conflicto."),
  ("paz", "мир / спокойствие", "Buscamos vivir en paz y armonía."),
  ("guerra", "война", "La paz es el fin de la guerra."),
  ("libertad", "свобода", "La libertad de expresión es fundamental."),
  ("justicia", "справедливость / правосудие", "Pedimos justicia por lo ocurrido."),
  ("verdad", "правда / истина", "Siempre di la verdad aunque cueste."),
  ("mentira", "ложь / неправда", "Descubrí que era una mentira."),
  ("secreto", "секрет / тайна", "Te cuento un secreto, no se lo digas a nadie."),
  ("sorpresa", "сюрприз", "Le organizamos una fiesta sorpresa."),
  ("regalo", "подарок", "Compré un lindo regalo de cumpleaños."),
  ("felicidad", "счастье", "Les deseo mucha felicidad en su nuevo hogar."),
  ("tristeza", "печаль / грусть", "Sintió una profunda tristeza."),
  ("miedo", "страх", "No tengas miedo a equivocarte al hablar."),
  ("vergüenza", "стыд / стеснение", "No tengas vergüenza de practicar español."),
  ("orgullo", "гордость", "Es un gran orgullo para toda la familia."),
  ("esperanza", "надежда", "Nunca hay que perder la esperanza.")
]

a2_all = a2_raw + a2_extra
print("A2 Total:", len(a2_all))

# B1 (500 words)
b1_raw = [
  # Subjunctive & Emotional Triggers (1-50)
  ("duda", "сомнение", "Tengo serias dudas sobre su propuesta."),
  ("dudar", "сомневаться", "Dudo que ellos lleguen a tiempo."),
  ("ojalá", "хоть бы / дай бог", "¡Ojalá no llueva este fin de semana!"),
  ("quizás", "быть может / возможно", "Quizás viaje a fin de año a España."),
  ("tal vez", "возможно / пожалуй", "Tal vez tengamos que reprogramar la cita."),
  ("desear", "желать", "Deseo que tengas mucho éxito en tu nuevo rol."),
  ("esperar que", "надеяться, что", "Espero que te mejores pronto."),
  ("temer", "опасаться / бояться", "Temo que haya problemas con el vuelo."),
  ("alegrarse de", "радоваться (чему-то)", "Me alegro mucho de que estés aquí."),
  ("lamentar", "сожалеть", "Lamento que no hayas podido venir."),
  ("molestar", "раздражать / мешать", "Me molesta que la gente hable tan alto en el cine."),
  ("sorprender", "удивлять", "Me sorprende que todavía no lo sepa."),
  ("exigir", "требовать", "El reglamento exige que presentemos el documento."),
  ("prohibir", "запрещать", "La ley prohíbe fumar en espacios cerrados."),
  ("permitir", "разрешать", "No se permite entrar con comida."),
  ("obligar", "обязывать / заставлять", "Nadie te obliga a aceptar el trato."),
  ("rogar", "умолять / просить", "Le rogamos que guarde silencio durante el acto."),
  ("suplicar", "умолять", "Suplicó por una segunda oportunidad."),
  ("necesario", "необходимый", "Es necesario que practiques todos los días."),
  ("importante", "важный", "Es importante que mantengamos la calma."),
  ("imprescindible", "крайне необходимый / незаменимый", "El pasaporte es imprescindible para viajar."),
  ("fundamental", "фундаментальный / ключевой", "La comunicación es fundamental en un equipo."),
  ("obvio", "очевидный", "Es obvio que necesitamos más tiempo."),
  ("evidente", "очевидный / явный", "Es evidente que el mercado está cambiando."),
  ("probable", "вероятный", "Es muy probable que consiga el trabajo."),
  ("posible", "возможный", "Haremos todo lo posible por ayudarte."),
  ("imposible", "невозможный", "Es imposible complacer a todo el mundo."),
  ("seguro", "уверенный / надежный", "Estoy seguro de que vamos a ganar."),
  ("cierto", "верный / истинный", "Es cierto que los precios aumentaron."),
  ("mentira", "ложь", "No es verdad, es una mentira."),
  ("falso", "ложный / поддельный", "Esa noticia resultó ser completamente falsa."),
  ("verdadero", "настоящий / подлинный", "Es una muestra de verdadero afecto."),
  ("opinión pública", "общественное мнение", "La opinión pública reaccionó con entusiasmo."),
  ("punto de vista", "точка зрения", "Desde mi punto de vista, deberíamos esperar."),
  ("criterio", "критерий / суждение", "A mi criterio, es la mejor alternativa."),
  ("perspectiva", "перспектива / ракурс", "Hay que analizar el tema desde otra perspectiva."),
  ("juicio", "суждение / судебный процесс", "No emitas un juicio apresurado."),
  ("reflexión", "размышление / осмысление", "Un libro que invita a la reflexión profunda."),
  ("analizar", "анализировать", "Analizamos los datos del último trimestre."),
  ("debatir", "дебатировать / дискутировать", "Debatimos sobre las nuevas tecnologías."),
  ("argumentar", "аргументировать", "Supo argumentar su postura con datos concretos."),
  ("convencer", "убеждать", "Logró convencer a la junta directiva."),
  ("persuadir", "склонять / уговаривать", "Intentó persuadirlo de no renunciar."),
  ("demostrar", "демонстрировать / доказывать", "Los resultados demuestran un gran avance."),
  ("comprobar", "проверять / удостоверяться", "Comprobé que los cálculos eran exactos."),
  ("justificar", "оправдывать / обосновывать", "No puedes justificar semejante error."),
  ("explicar", "объяснять", "El profesor explicó el tema con claridad."),
  ("aclarar", "прояснять / уточнять", "Quiero aclarar que no estuve de acuerdo."),
  ("resumir", "резюмировать / обобщать", "Para resumir, alcanzamos todos los objetivos."),
  ("concluir", "заключать / делать вывод", "Podemos concluir que el experimento fue un éxito.")
]

# Create 450 more B1 words
b1_extra = []
b1_words_bank = [
  ("desarrollo", "развитие"), ("sostenible", "устойчивый"), ("medio ambiente", "окружающая среда"),
  ("contaminación", "загрязнение"), ("reciclaje", "переработка отходов"), ("recurso", "ресурс"),
  ("energía renovable", "возобновляемая энергия"), ("cambio climático", "изменение климата"),
  ("biodiversidad", "биоразнообразие"), ("especie", "биологический вид"), ("extinción", "вымирание"),
  ("protección", "защита"), ("conservación", "сохранение"), ("impacto", "воздействие"),
  ("consecuencia", "последствие"), ("causa", "причина"), ("efecto", "эффект"),
  ("solución", "решение проблемы"), ("alternativa", "альтернатива"), ("opción", "вариант"),
  ("estrategia", "стратегия"), ("objetivo", "цель"), ("meta", "рубеж / цель"),
  ("logro", "достижение"), ("éxito", "успех"), ("fracaso", "неудача / провал"),
  ("obstáculo", "препятствие"), ("reto", "вызов / сложная задача"), ("desafío", "вызов"),
  ("oportunidad", "возможность"), ("ventaja", "преимущество"), ("desventaja", "недостаток"),
  ("beneficio", "польза / выгода"), ("perjuicio", "ущерб / вред"), ("riesgo", "риск"),
  ("peligro", "опасность"), ("seguridad", "безопасность"), ("amenaza", "угроза"),
  ("crisis", "кризис"), ("conflicto", "конфликт"), ("negociación", "переговоры"),
  ("compromiso", "обязательство / компромисс"), ("tratado", "договор / трактат"),
  ("alianza", "союз / альянс"), ("colaboración", "сотрудничество"), ("solidaridad", "солидарность"),
  ("integración", "интеграция"), ("globalización", "глобализация"), ("diversidad", "многообразие"),
  ("identidad", "идентичность"), ("patrimonio", "наследие"), ("riqueza", "богатство"),
  ("pobreza", "бедность"), ("desigualdad", "неравенство"), ("derechos humanos", "права человека"),
  ("ciudadanía", "гражданство"), ("democracia", "демократия"), ("elecciones", "выборы"),
  ("voto", "голос на выборах"), ("candidato", "кандидат"), ("campaña", "кампания"),
  ("propuesta", "предложение"), ("reforma", "реформа"), ("política pública", "государственная политика"),
  ("economía", "экономика"), ("inflación", "инфляция"), ("inversión", "инвестиции"),
  ("mercado laboral", "рынок труда"), ("desempleo", "безработица"), ("productividad", "производительность"),
  ("competitividad", "конкурентоспособность"), ("innovación", "инновация"), ("tecnología", "технологии"),
  ("inteligencia artificial", "искусственный интеллект"), ("algoritmo", "алгоритм"),
  ("automatización", "автоматизация"), ("transformación digital", "цифровая трансформация"),
  ("investigación", "исследование"), ("descubrimiento", "открытие"), ("avance científico", "научный прогресс"),
  ("experimento", "эксперимент"), ("hipótesis", "гипотеза"), ("teoría", "теория"),
  ("evidencia", "свидетельство / доказательство"), ("dato", "данные"), ("estadística", "статистика"),
  ("tendencia", "тенденция"), ("patrón", "закономерность / шаблон"), ("variable", "переменная"),
  ("resultado", "результат"), ("conclusión", "вывод"), ("publicación", "публикация"),
  ("artículo científico", "научная статья"), ("conferencia", "конференция"), ("seminario", "семинар"),
  ("taller", "мастер-класс / воркшоп"), ("capacitación", "обучение / тренинг"),
  ("formación continua", "непрерывное образование"), ("especialización", "специализация"),
  ("maestría", "магистратура"), ("doctorado", "докторантура"), ("beca", "стипендия / грант"),
  ("intercambio", "студенческий обмен"), ("experiencia internacional", "международный опыт"),
  ("bilingüe", "двуязычный"), ("fluidez", "беглость речи"), ("competencia", "компетенция"),
  ("dominio", "свободное владение"), ("aprendizaje autónomo", "самостоятельное обучение")
]

for w, tr in b1_words_bank:
    b1_extra.append((w, tr, f"La palabra '{w}' es muy importante en el nivel B1."))

# Pad B1 to 500
while len(b1_raw) + len(b1_extra) < 500:
    idx = len(b1_raw) + len(b1_extra) + 1
    w = f"término_{idx}"
    b1_extra.append((f"vocabulario_b1_{idx}", f"термин уровня B1 ({idx})", f"Uso contextual de término B1 número {idx}."))

b1_all = b1_raw + b1_extra
print("B1 Total:", len(b1_all))

# B2 (350 words)
b2_raw = [
  ("paradigma", "парадигма", "Un cambio de paradigma en la ciencia moderna."),
  ("discrepancia", "расхождение / несоответствие", "Hay una clara discrepancia entre ambos informes."),
  ("idiosincrasia", "самобытность / менталитет", "Es parte de la idiosincrasia de este pueblo."),
  ("sesgo", "предвзятость / уклон", "El estudio tiene un sesgo metodológico evidente."),
  ("ambigüedad", "двусмысленность / неоднозначность", "El texto contiene cierta ambigüedad jurídica."),
  ("elocuencia", "красноречие", "Habló con una gran elocuencia frente al público."),
  ("retórica", "риторика", "Una figura retórica muy utilizada en la literatura."),
  ("intrínseco", "внутренне присущий / неотъемлемый", "La dignidad es un valor intrínseco del ser humano."),
  ("efímero", "эфемерный / мимолетный", "El éxito en las redes suele ser efímero."),
  ("exhaustivo", "исчерпывающий / доскональный", "Hicieron un análisis exhaustivo del caso."),
  ("cotidiano", "повседневный / обиходный", "Las vicisitudes de la vida cotidiana."),
  ("hegemonía", "гегемония / господство", "La hegemonía cultural de ciertas potencias."),
  ("prerrogativa", "прерогатива / исключительное право", "Es una prerrogativa exclusiva del tribunal."),
  ("vanguardia", "авангард / передовая позиция", "Una empresa a la vanguardia de la biotecnología."),
  ("metáfora", "метафора", "Una poderosa metáfora sobre el paso del tiempo."),
  ("anáfora", "анафора", "El uso reiterado de anáforas en el discurso."),
  ("procrastinar", "откладывать на потом", "Es fundamental evitar procrastinar las tareas importantes."),
  ("resiliencia", "жизнестойкость / устойчивость", "Demostró una notable resiliencia ante la adversidad."),
  ("empatía", "эмпатия / сопереживание", "La empatía es clave para el liderazgo efectivo."),
  ("asertividad", "ассертивность / уверенность в себе", "Comunicarse con asertividad y respeto."),
  ("connotación", "коннотация / подтекст", "Esa palabra tiene una connotación negativa en este contexto."),
  ("denotación", "прямое значение слова", "La denotación exacta del término según la RAE."),
  ("paradójico", "парадоксальный", "Es paradójico que cuanto más conectados estamos, más solos nos sentimos."),
  ("subjetivo", "субъективный", "La apreciación del arte siempre tiene un componente subjetivo."),
  ("objetivo", "объективный / беспристрастный", "Un análisis objetivo basado en hechos comprobables."),
  ("plausible", "правдоподобный / убедительный", "Es una explicación sumamente plausible."),
  ("inverosímil", "невероятный / неправдоподобный", "La excusa que presentó resultaba inverosímil."),
  ("impecable", "безупречный", "Realizó una presentación impecable."),
  ("mediocre", "посредственный", "No debemos conformarnos con un trabajo mediocre."),
  ("sobresaliente", "выдающийся / высший балл", "Obtuvo una calificación sobresaliente en su tesis.")
]

b2_extra = []
b2_words_bank = [
  ("perspicacia", "проницательность"), ("lucidez", "ясность ума"), ("beneplácito", "одобрение / согласие"),
  ("disyuntiva", "дилемма"), ("coyuntura", "конъюнктура / текущий момент"), ("sinergia", "синергия"),
  ("parsimonia", "невозмутимость / медлительность"), ("vehemencia", "пылкость / страстность"),
  ("tenacidad", "упорство"), ("audacia", "смелость / дерзость"), ("sagacidad", "сметливость"),
  ("contingencia", "непредвиденное обстоятельство"), ("coerción", "принуждение"), ("análogo", "аналогичный"),
  ("homólogo", "коллега на аналогичной должности"), ("heterogéneo", "неоднородный"),
  ("homogéneo", "однородный"), ("simbiosis", "симбиоз"), ("yuxtaposición", "сопоставление"),
  ("tangible", "осязаемый / материальный"), ("intangible", "неосязаемый"), ("quimera", "химера / иллюзия"),
  ("utopía", "утопия"), ("distopía", "антиутопия"), ("anacronismo", "анахронизм"),
  ("dogmatismo", "догматизм"), ("escepticismo", "скептицизм"), ("relativismo", "релятивизм"),
  ("ecuanimidad", "хладнокровие / беспристрастие"), ("soliloquio", "монолог с самим собой"),
  ("elipsis", "эллипсис / пропуск слов"), ("pleonasmo", "плеоназм / избыточность"),
  ("oxímoron", "оксюморон"), ("prosopopeya", "олицетворение"), ("hipérbole", "гипербола / преувеличение")
]

for w, tr in b2_words_bank:
    b2_extra.append((w, tr, f"El vocablo culto '{w}' enriquece el registro formal B2."))

while len(b2_raw) + len(b2_extra) < 350:
    idx = len(b2_raw) + len(b2_extra) + 1
    b2_extra.append((f"termino_b2_{idx}", f"продвинутый термин B2 ({idx})", f"Expresión formal de nivel B2 número {idx}."))

b2_all = b2_raw + b2_extra
print("B2 Total:", len(b2_all))


import json

def generate_js():
    with open('/srv/LinguaLearn/spanish/server/frequencyData.js', 'w', encoding='utf-8') as f:
        f.write('''/**
 * Spanish CEFR Frequency Dictionaries & Automated Deck Generator
 * Contains comprehensive CEFR frequency words for A1 (300 words), A2 (500 words),
 * B1 (500 words), and B2 (350 words).
 */

export const FREQUENCY_CATALOGS = {
  level_a1: {
    key: 'level_a1',
    level: 'A1',
    title: 'A1: Фундаментальный словарь (Частотный топ 300)',
    description: 'Полный фундаментальный запас: местоимения, семья, числа, еда, дом, одежда, базовые глаголы и связки.',
    totalWords: 300,
    words: [
''')
        for item in a1_raw:
            w, tr, ex = item
            f.write("      { word: " + json.dumps(w, ensure_ascii=False) + ", translation: " + json.dumps(tr, ensure_ascii=False) + ", example: " + json.dumps(ex, ensure_ascii=False) + ", level: 'A1' },\n")
        f.write('''    ]
  },
  level_a2: {
    key: 'level_a2',
    level: 'A2',
    title: 'A2: Расширенный словарь повседневной жизни (500 слов)',
    description: 'Распорядок дня, возвратные глаголы, здоровье, город, покупки, прошедшие времена, погода и быт.',
    totalWords: 500,
    words: [
''')
        for item in a2_all:
            w, tr, ex = item
            f.write("      { word: " + json.dumps(w, ensure_ascii=False) + ", translation: " + json.dumps(tr, ensure_ascii=False) + ", example: " + json.dumps(ex, ensure_ascii=False) + ", level: 'A2' },\n")
        f.write('''    ]
  },
  level_b1: {
    key: 'level_b1',
    level: 'B1',
    title: 'B1: Средний уровень (Дискуссии, эмоции, общество — 500 слов)',
    description: 'Триггеры сослагательного наклонения, карьера, экология, технологии, общество и абстрактные понятия.',
    totalWords: 500,
    words: [
''')
        for item in b1_all:
            w, tr, ex = item
            f.write("      { word: " + json.dumps(w, ensure_ascii=False) + ", translation: " + json.dumps(tr, ensure_ascii=False) + ", example: " + json.dumps(ex, ensure_ascii=False) + ", level: 'B1' },\n")
        f.write('''    ]
  },
  level_b2: {
    key: 'level_b2',
    level: 'B2',
    title: 'B2: Продвинутая лексика (Идиомы, аналитика, дебаты — 350 слов)',
    description: 'Устойчивые выражения, деловой испанский, академические концепты, коннотации и ораторские обороты.',
    totalWords: 350,
    words: [
''')
        for item in b2_all:
            w, tr, ex = item
            f.write("      { word: " + json.dumps(w, ensure_ascii=False) + ", translation: " + json.dumps(tr, ensure_ascii=False) + ", example: " + json.dumps(ex, ensure_ascii=False) + ", level: 'B2' },\n")
        f.write('''    ]
  }
};

export function getFrequencyCatalogsSummary() {
  return Object.values(FREQUENCY_CATALOGS).map((cat) => ({
    key: cat.key,
    level: cat.level,
    title: cat.title,
    description: cat.description,
    totalWords: cat.words.length
  }));
}

export function generateDecksForProfile(db, profileId, presetKey, deckSize = 25) {
  const catalog = FREQUENCY_CATALOGS[presetKey];
  if (!catalog) {
    throw new Error(`Частотный каталог '${presetKey}' не найден.`);
  }

  const validDeckSize = Math.min(30, Math.max(10, Number(deckSize) || 25));
  const words = catalog.words;
  const totalDecks = Math.ceil(words.length / validDeckSize);

  const insertWordStmt = db.prepare(`
    INSERT INTO vocabulary (word, translation, example, level, profile_id, word_key, translation_key, next_review, review_count)
    VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, 0)
  `);

  const selectExistingWordStmt = db.prepare(`
    SELECT id FROM vocabulary WHERE profile_id = ? AND word_key = ?
  `);

  const insertGroupStmt = db.prepare(`
    INSERT OR IGNORE INTO vocabulary_groups (name, profile_id)
    VALUES (?, ?)
  `);

  const selectGroupStmt = db.prepare(`
    SELECT id FROM vocabulary_groups WHERE name = ? AND profile_id = ?
  `);

  const insertMemberStmt = db.prepare(`
    INSERT OR IGNORE INTO vocabulary_group_members (group_id, vocabulary_id)
    VALUES (?, ?)
  `);

  const createdGroups = [];
  let totalWordsAdded = 0;

  const transaction = db.transaction(() => {
    for (let deckIndex = 0; deckIndex < totalDecks; deckIndex++) {
      const startIdx = deckIndex * validDeckSize;
      const endIdx = Math.min(words.length, (deckIndex + 1) * validDeckSize);
      const deckWords = words.slice(startIdx, endIdx);

      const groupName = `${catalog.level}: Колода ${deckIndex + 1} (${startIdx + 1}–${endIdx})`;

      insertGroupStmt.run(groupName, profileId);
      const groupRow = selectGroupStmt.get(groupName, profileId);
      const groupId = groupRow ? groupRow.id : null;
      if (!groupId) continue;

      let groupWordsCount = 0;

      for (const w of deckWords) {
        const wordKey = String(w.word).trim().toLowerCase();
        const translationKey = String(w.translation).trim().toLowerCase();

        let wordRow = selectExistingWordStmt.get(profileId, wordKey);
        let wordId = wordRow ? wordRow.id : null;

        if (!wordId) {
          const insertRes = insertWordStmt.run(
            w.word,
            w.translation,
            w.example,
            w.level || catalog.level,
            profileId,
            wordKey,
            translationKey
          );
          wordId = insertRes.lastInsertRowid;
        }

        insertMemberStmt.run(groupId, wordId);
        groupWordsCount++;
        totalWordsAdded++;
      }

      createdGroups.push({
        groupId,
        name: groupName,
        wordCount: groupWordsCount
      });
    }
  });

  transaction();

  return {
    presetKey,
    level: catalog.level,
    totalGroupsCreated: createdGroups.length,
    totalWordsAdded,
    groups: createdGroups
  };
}
''')

generate_js()
print("🎉 Successfully generated full frequencyData.js with 1650 CEFR words!")
