services:
  auto_matcher:
    container_name: auto_matcher
    entrypoint: /auto_matcher
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "7050:7001"
    env_file:
      - ./.env
    environment:
      - MODE=live
    volumes:
      - ./configs:/configs:ro
    networks:
      - livebets

networks:
  livebets:
    external: true
