services:
  auto_matcher_prematch:
    container_name: auto_matcher_prematch
    entrypoint: /auto_matcher
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "7051:7001"
    env_file:
      - ./.env.prematch
    environment:
      - MODE=prematch
    volumes:
      - ./configs:/configs:ro
    networks:
      - livebets

networks:
  livebets:
    external: true
