services:
  admin_cli:
    container_name: admin_cli
    image: frontend-admin_cli
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:31562:31562"
    restart: always
    env_file:
      - .env.local
    environment:
      ANALYZER_HOST: analyzer
      ANALYZER_PREMATCH_HOST: analyzer_prematch
    volumes:
      - /srv/big_value/monitoring/services-config.json:/srv/big_value/monitoring/services-config.json:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - livebets

networks:
  livebets:
    external: true
